### ISSUE TITLE
Unable to scroll the documentation menu when at a small breakpoint 

### ISSUE THREAD

**Issue by superhighfives** [styled-components/styled-components-website#10]
When visiting https://sc-next-docs.philpl.com/docs at a smaller breakpoint, the overlay menu doesn't allow scrolling on desktop (OSX, Chrome 57).

On mobile (iOS 10, Safari) it seems a bit touch and go whether you're scrolling the overlay menu or the body itself.

![screen shot 2017-05-11 at 14 05 16](https://cloud.githubusercontent.com/assets/449385/25951589/143acb98-3656-11e7-8bd9-7330fb88b8e8.png)

**Comment by philpl** [comment]
Thanks for reporting! I'll take a look
