### ISSUE TITLE
Add syntax highlighting setup to tooling

### ISSUE THREAD

**Issue by mxstbr** [styled-components/styled-components-website#101]
We should add docs about all the syntax highlighters for all the different editors to the website so people can find it!

**Comment by SaraVieira** [comment]
Hello @mxstbr! 

What syntax highlighters are there?

**Comment by philpl** [comment]
@SaraVieira Most of them are listed here: https://github.com/styled-components/styled-components#syntax-highlighting

A new addition is the WebStorm plugin: https://github.com/styled-components/webstorm-styled-components

**Comment by SaraVieira** [comment]
@philpl I can take this on tonight 😀

Is it okay if I use the icon for the apps ?

**Comment by mxstbr** [comment]
Sure!

**Comment by SaraVieira** [comment]
@mxstbr Should this also include a PR to the styled-components readme to remove all the documentation from there ?

**Comment by morajabi** [comment]
@SaraVieira I think we can have a paragraph in that repo with a link to the new section for the information. Also, we need to mention which editors/IDEs we support in that paragraph so they know whether the ext for their editor is available or not, right there. (IMO)

**Comment by philpl** [comment]
@morajabi I agree, we should replace the section, but still mention the editors we support :)

**Comment by SaraVieira** [comment]
Fishnuggets! I forgot about this! I will start again on this today :)

It will be a new page on tooling? @mxstbr @morajábig @philpl

**Comment by morajabi** [comment]
@morajáBIG ? I'm not BIG. 😆

**Comment by mxstbr** [comment]
Hahaha love that typo!

Yeah, should be in tooling @SaraVieira. Call it "Syntax highlighting" or something like that!

**Comment by mxstbr** [comment]
@SaraVieira any chance you could pick this up based on https://github.com/styled-components/styled-components/pull/1367? :blush:

**Comment by SaraVieira** [comment]
YES ! I'm so sorry I have been somehow out but I do have time this week 🤗
Added to calendar so that I don't forget

<img width="716" alt="screen shot 2017-12-18 at 10 19 47" src="https://user-images.githubusercontent.com/1051509/34101243-012a9d78-e3dd-11e7-931d-f476d88f0a02.png">
