### ISSUE TITLE
Can't link to headings on API page

### ISSUE THREAD

**Issue by mxstbr** [styled-components/styled-components-website#105]
One can't link to headings on the API page. They are `<code>` blocks and our slugifier obviously doesn't know what to do with that:

![screen shot 2017-09-04 at 11 03 43 am](https://user-images.githubusercontent.com/7525670/30019399-c369cd48-9160-11e7-8800-73a05f436e9b.png)

We should get that fixed as it's pretty annoying!

**Comment by philpl** [comment]
@mxstbr hm I thought I fixed the stringifier. I’ll take a look this afternoon

**Comment by morajabi** [comment]
Just discovered there's another problem when there's a code block in the title:
This
![screen shot 2017-09-14 at 5 06 06 pm](https://user-images.githubusercontent.com/12202757/30430038-14b307bc-996f-11e7-8090-cd3e3c6a1267.png)
Does not match the link in the home page:
![screen shot 2017-09-14 at 5 07 14 pm](https://user-images.githubusercontent.com/12202757/30430069-3af83f50-996f-11e7-8061-440e2a620467.png)

**Comment by morajabi** [comment]
@mxstbr BTW, I don't see any problems there:
![screen shot 2017-09-14 at 5 06 06 pm](https://user-images.githubusercontent.com/12202757/30430433-73ff7b28-9970-11e7-825f-0a169c8b6600.png)

**Comment by morajabi** [comment]
@philpl Did you see this and #112?

**Comment by philpl** [comment]
This should now be fixed in https://github.com/styled-components/styled-components-website/pull/153

The original bug in this issue was fixed a while ago, but the slugifier was still behaving incorrectly.
