### ISSUE TITLE
Figure out relevant navbar links

### ISSUE THREAD

**Issue by philpl** [styled-components/styled-components-website#115]
https://github.com/styled-components/styled-components-website/blob/master/components/Nav/NavLinks.js#L40

In the navbar we're currently showing:

- Concepts (`/docs/basics/#motivation`)
- Try it out (`/`)
- Documentation (`/docs`)

My idea would be to remove "Concepts" as it's not a top-level page (and the wrong title), and leave the other two, until we have more pages, like "Wall of Love".

"Try it out" is great for what it does, but should we call it "Home" or something else that's neutral instead?

cc @mxstbr

**Comment by ZackTaylor** [comment]
I'd like to take care of this would the fix be just removing:
```
<NavLink href="/docs/basics#motivation">Concepts</NavLink>
    <NavSeparator />
```
Are there any other links you'd like me to add?

**Comment by philpl** [comment]
@ZackTaylor That and renaming `Try it out` to `Homepage` or sth similar, I suppose. Maybe @mxstbr has more ideas?

**Comment by mxstbr** [comment]
Yeah that sounds great, let's just get that done and ship it!

**Comment by philpl** [comment]
@ZackTaylor Are you still interested in helping with this btw? If you're busy at the moment, no worries 👍 , we have enough other tasks for everyone, but this is the only one that holds up a new release of the site right now :wink:

**Comment by ZackTaylor** [comment]
Yes I'll take a shot at this right now!

**Comment by ZackTaylor** [comment]
Ok yall made a PR let me know if everything looks good.

**Comment by mxstbr** [comment]
This is fixed, thanks to @ZackTaylor!
