### ISSUE TITLE
Theming section is missing information on the "manual" theme prop

### ISSUE THREAD

**Issue by philpl** [styled-components/styled-components-website#116]
It's possible to circumvent a missing `ThemeProvider` or override it with the `theme` prop.

We're not noting that the `theme` prop is reserved and how it can be used.

https://github.com/styled-components/styled-components/blob/master/src/models/StyledComponent.js#L110

**Comment by tejasbubane** [comment]
I think this can be closed now.

**Comment by mxstbr** [comment]
Yep, good catch, thanks @tejasbubane!
