### ISSUE TITLE
css`` syntax highlighting does not work inside styled``

### ISSUE THREAD

**Issue by oomathias** [styled-components/styled-components-website#117]
I'm using `prismTemplateString.js` inside my project for documentation purpose and I saw that `css` nested inside `styled` are not colorized properly.

Here is an example from `styled-components` homepage. 

![image](https://user-images.githubusercontent.com/465790/30918192-17f27b4a-a39e-11e7-9fa1-bf1436e7114f.png)

Is that a limitation from PrismJS or a bug?

**Comment by philpl** [comment]
It's a tricky one to get right!

If you'd like to give it a try, take a look at: https://github.com/styled-components/styled-components-website/blob/master/utils/prismTemplateString.js

**Comment by stevemao** [comment]
@oomathias Why is it closed? Is there a PR open?

**Comment by oomathias** [comment]
I can reopen it if needed. I was cleaning my issues and checked https://www.styled-components.com which now displays the correct color syntax, so I'm guessing someone fixed it.

![screenshot](https://user-images.githubusercontent.com/465790/51086704-2b1f4880-174a-11e9-84a2-4f99993cfd52.png)
