### ISSUE TITLE
Add structured data

### ISSUE THREAD

**Issue by mxstbr** [styled-components/styled-components-website#129]
We could use some schema.org structured data to look better in Google Search Results!

**Comment by morajabi** [comment]
I think we need a better title for the home page too. It shouldn't be just the package name. We can update it like this for example: *styled components - Visual primitives for the component age* or

**Comment by morajabi** [comment]
As you said, having these kind of links in Google would be useful/beautiful:
<img width="615" alt="screen shot 2017-10-05 at 11 39 59 am" src="https://user-images.githubusercontent.com/12202757/31216888-f923433c-a9c1-11e7-934f-5b3a13e3ffc1.png">
<img width="502" alt="screen shot 2017-10-05 at 11 39 52 am" src="https://user-images.githubusercontent.com/12202757/31216889-f9307d4a-a9c1-11e7-8f45-26dc0565139b.png">

**Comment by mxstbr** [comment]
Yep, that's what I'm looking for!

**Comment by morajabi** [comment]
But I think one of the reasons we don't have those is we don't have any `<nav>` in our home page. :(

**Comment by mxstbr** [comment]
Hmm, I don't know! Let's give it a try?

**Comment by morajabi** [comment]
Anyway, @philpl said we need the navbar for the homepage!

**Comment by imbhargav5** [comment]
@mxstbr Closing this as this seems to have been fixed.
