### ISSUE TITLE
Move Babel plugin docs to website

### ISSUE THREAD

**Issue by mxstbr** [styled-components/styled-components-website#13]
Those don't make any sense to live in the repo, they should be on the website too! (especially once we move to a mono-repo)

**Comment by SaraVieira** [comment]
@mxstbr You mean passing these docs : https://github.com/styled-components/babel-plugin-styled-components to the webiste ?

**Comment by philpl** [comment]
@SaraVieira yes, we'll need to add a section for it to the API section, and add some notes to some others to point to it :)

**Comment by SaraVieira** [comment]
I can take this on?

**Comment by SaraVieira** [comment]
@philpl Can I take this on? :) 

_Sent from my Bq Aquaris M5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by philpl** [comment]
@SaraVieira sure! We appreciate all the help we can get :)

**Comment by mxstbr** [comment]
Please do it @SaraVieira! I'd love to have them on the website!

**Comment by SaraVieira** [comment]
@mxstbr @philpl On it !
