### ISSUE TITLE
Improve inline code styling

### ISSUE THREAD

**Issue by mxstbr** [styled-components/styled-components-website#130]
I think our current inline code styling isn't brilliant:

![screen shot 2017-10-05 at 11 32 29 am](https://user-images.githubusercontent.com/7525670/31220537-039ce800-a9c1-11e7-86c8-f75e883a9924.png)

It sticks out of the text like a sore thumb. I much more like GitHubs treatment of `inline code`, but I feel like we just gotta find something that's less obvious and flows better when reading.

**Comment by morajabi** [comment]
Totally agree with this. Can you tell me more about your preference so I can do some sketches?

**Comment by mxstbr** [comment]
No preferences or sketches, happy to review a couple ideas!

**Comment by morajabi** [comment]
OK, let's start with the problems with "current style" and the "Github style".
