### ISSUE TITLE
Fix Ecosystem sidebar to use the page headings

### ISSUE THREAD

**Issue by morajabi** [styled-components/styled-components-website#131]
@philpl 
> The navbar and sidebar are pretty static and unconfigurable at the moment 😢, However, we'll need to include the navbar on the homepage eventually, and we'll need to grab all the headers (## ...) and generate an alternative sidebar for this page.

We need to grab all headings from the Ecosystem page and build the proper sidebar for this specific page.

**Comment by chinesedfan** [comment]
@morajabi Already done by #143?

**Comment by mxstbr** [comment]
Good catch @chinesedfan!

**Comment by morajabi** [comment]
Oh, it feels good looking how much we've done 😊
