### ISSUE TITLE
innerRef example uses `this` where `this` is the window object

### ISSUE THREAD

**Issue by sk22** [styled-components/styled-components-website#136]
In https://www.styled-components.com/docs/advanced#refs, the code says this:

```javascript
const Form = () => (
  <Input
    placeholder="Hover here..."
    innerRef={x => this.input = x}
    onMouseEnter={() => this.input.focus()}
  />
);
```

Since the `Form` component is written as an arrow function, I got confused of the use of `this`, as there's no `this` the `innerRef` and `onMouseEnter` props could use but the global scope. And indeed, after hovering over the text box, `window.input` contains the reference to the input element.

Please change that, because it's bad practice to store variables in the global scope.

**Comment by sk22** [comment]
The example here does it better: https://github.com/styled-components/styled-components/blob/master/docs/tips-and-tricks.md#refs-to-dom-nodes

**Comment by mxstbr** [comment]
PR to clean this up very welcome!

**Comment by glhrmv** [comment]
I'll work on this.

**Comment by glhrmv** [comment]
I've submitted #139. Couldn't extend just `Component` so I hope this is fine.

**Comment by mxstbr** [comment]
Thanks @glhrmv!
