### ISSUE TITLE
Add "Hosted on ZEIT Now" shoutout

### ISSUE THREAD

**Issue by philpl** [styled-components/styled-components-website#155]
@rauchg will set us up with a sponsorship plan on Now, so we should add a "Hosted on ZEIT Now" shoutout asap to the website.

cc @mxstbr

**Comment by morajabi** [comment]
Do you have a particular place for that in mind?

**Comment by philpl** [comment]
@morajabi the footer with the author names I guess. I'll throw it together quickly

**Comment by morajabi** [comment]
Isn't the padding a bit off? In terms of design? Also, what do you think about changing the footer bg to something lighter or darker?

**Comment by philpl** [comment]
@morajabi we can fix that in a separate PR. I'm not a big fan of making it darker since it calls upon the colour that is already used in the gradient and navbar. But I'd like to remove the shadow, add a translucent black gradient that makes it darker at the bottom, decrease the height, and recentre it. But yea, separate PR, separate issue

**Comment by philpl** [comment]
Deployed; should be up after the Cloudflare cache clears itself (max 24h)
