### ISSUE TITLE
Redesign that Footer (🎃)

### ISSUE THREAD

**Issue by morajabi** [styled-components/styled-components-website#157]
I'll try to sketch something quickly.

**Comment by philpl** [comment]
Copied from the other issue:

- remove the shadow
- add a translucent black gradient that makes it darker at the bottom (? let's see if that works)
- decrease the height
- recentre content
- (maybe) increase margin

**Comment by morajabi** [comment]
@philpl I don't understand what do you mean by "translucent black gradient" exactly? Sorry!

**Comment by philpl** [comment]
@morajabi a gradient above the darkened pale violet red. So optimally a linear gradient that goes from a darker version of the colour from the bottom to a lighter one at the top

**Comment by morajabi** [comment]
@philpl https://www.figma.com/file/ZZHoPeTYKNtNqcLYnRsQSVxR/Styled-Components
Check this. I haven't changed the layout but we can do that if we want to include more links in the footer.

**Comment by philpl** [comment]
@morajabi I really like the grey actually. Since that corresponds to our sidebar and navbar, that's fine to me as well :+1:

**Comment by mxstbr** [comment]
Done thanks to @tomvaneygen!
