### ISSUE TITLE
Add "Users" page with a list of companies who're using SC

### ISSUE THREAD

**Issue by kitten** [styled-components/styled-components-website#16]

**Comment by mxstbr** [comment]
Here's an imcomplete list to get started with, sorted by my own personal order of importance. The first group are the ones that should also go on the homepage imo:

- reddit ([src](https://twitter.com/griffinmichl/status/859637366004346880))
- Bloomberg ([src](https://twitter.com/dmueller39/status/866061486120202243))
- Target ([src](https://twitter.com/Fuller_AJ/status/854487908782399488))
- Eurovision Song Contest ([src](https://twitter.com/rovansteen/status/854602658979696640))
- Ideo ([src](https://twitter.com/aaronabentheuer/status/854443801074708482))
- Atlassian (source: me)

----

- swat.io ([src](https://twitter.com/stnwk/status/854440975908962304))
- University of Alabama ([src](https://twitter.com/costonperkins/status/854438614033457157))
- The League of Movable Type ([src](https://twitter.com/micahbrich/status/854603229845475328))
- Artsy ([src](https://twitter.com/orta/status/854438342636777477))
- AdaHealth ([src](https://twitter.com/boennemann/status/863481711954460672))
- Bleacher Report ([src](https://twitter.com/b_hough/status/854438476602908672))
- shop.com ([src](https://twitter.com/VinceKerrazzi/status/854703695270903808))
- Once It ([src](https://twitter.com/whatyoubendoing/status/859621922962911233))
- Werkspot ([src](https://twitter.com/kureevalexey/status/854646041840373760))
- Practo ([src](https://twitter.com/siddharthkp/status/854542804923555840))
- Sperahealth ([src](https://twitter.com/_matthamil/status/854460729960935428))
- MoxeHealth ([src](https://twitter.com/jonmajorc/status/854467388615602176)) 
- GS&F ([src](https://twitter.com/knightblake/status/854447170350600193))
- Made Awkward ([src](https://twitter.com/timonvspronsen/status/854692595221630977))
- Editket ([src](https://twitter.com/5105_9825/status/854533251188183040))
- Perkbos ([src](https://twitter.com/GGilbertH/status/854464339490873344))
- DoorDash (internally, [src](https://twitter.com/ryngonzalez/status/854658038396887041))
- AlphaSights (internally, [src](https://twitter.com/perezpriego7/status/854684692834127874))

**Comment by philpl** [comment]
Artsy is really well known :) Should probably go into the page as well

**Comment by mxstbr** [comment]
Some first logos for the frontpage companies:

- [Bloomberg](https://upload.wikimedia.org/wikipedia/commons/5/5d/New_Bloomberg_Logo.svg) 
- [reddit](https://upload.wikimedia.org/wikipedia/commons/b/b4/Reddit_logo.svg)
- [Target](https://upload.wikimedia.org/wikipedia/commons/c/c5/Target_Corporation_logo_%28vector%29.svg) (couldn't find one with text)
- [Eurovision](https://upload.wikimedia.org/wikipedia/de/e/e1/Eurovision_Song_Contest.svg)
- [Atlassian](https://upload.wikimedia.org/wikipedia/commons/4/4d/Atlassian-logo.svg)
- [Artsy](https://upload.wikimedia.org/wikipedia/commons/b/bd/Art.sylogo_2.tiff) 

Let's put these on the homepage and delay the `/users` page until after v2?

**Comment by philpl** [comment]
can delay that yea :)

**Comment by mxstbr** [comment]
Invision are using it, but nothing public yet. Source: https://twitter.com/joshmatz/status/868126633303175168

**Comment by SaraVieira** [comment]
@mxstbr @philpl Can I take a crack at creating the users page ?

**Comment by philpl** [comment]
@SaraVieira you sure can but ehem ^^” I haven’t designed the homepage yet :D but if you’ve got time to start iterating on that as well I’d be eternally grateful :)

**Comment by SaraVieira** [comment]
@philpl you want all of this in the homepage then? In a section at the bottom? 

_Sent from my Bq Aquaris M5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by philpl** [comment]
@SaraVieira before we were discussing a Mac bar similar to the one on babel’s site :) that’d give the pages a little more visibility and reach

**Comment by mxstbr** [comment]
Yeah I'd leave the current logos where they are, make them link to `/users` and then have a long list of all of them (randomized?) on `/users` similar to Babels `/users`.

Would love a PR for that!

**Comment by SaraVieira** [comment]
@mxstbr @philpl butbthe current logos on the homepage would always be the same, not randomized right,?

**Comment by mxstbr** [comment]
Yeah we would want those to be the ones we have there now since they are the biggest names! :blush:

**Comment by SaraVieira** [comment]
Yes sir! I will just wait for my PR to be merged because I just can't work without prettier anymore 🙁
So I'll probably start this tonight

**Comment by philpl** [comment]
@SaraVieira I can merge it once you give me the go 👍 :tada: Thanks again! Ping me on Spectrum / Gitter / Twitter DMs if you'd like me to work on some designs for you :smile: I just need the appropriate shove, to put some time aside for it. Sorry for that 😭

**Comment by SaraVieira** [comment]
@philpl there are designs for the pages? Can I see them? I can iterate with you 

I'm trying to become a full stack ninja 😛

Maybe just a ninja xD

**Comment by mxstbr** [comment]
I don't think there's designs go whip something up! For reference, I really like how on Babels users page every logo has the same size: http://babeljs.io/users

**Comment by mxstbr** [comment]
Also, it's vital that the page is easy to add to. I want people to be able to add their company with a simple addition in some way which we then either randomise when displayed or sort by when they got on board or by how important we think the logo is. (`users.json`? Maybe there's something easier)

**Comment by SaraVieira** [comment]
@mxstbr my idea was a json already so that people could simply change it so I got you covered 😛

**Comment by el1f** [comment]
Is this one still up for grabs?

**Comment by probablyup** [comment]
I think this is probably superceded by the logo carousel

**Comment by mxstbr** [comment]
I would still love to have a `/users` page that lists all users and links to the websites that they built with s-c (if they are public)! The carousel is sweet but a bit hard to see as there are so many logos already that it takes a couple minutes to cycle through them all.

A good first step would be to simply take all the logos we already have and render them as a list below each other, similar to [the Babel users page](https://babeljs.io/en/users.html). Feel free to take that on @el1f!

**Comment by mxstbr** [comment]
Actually, I would rather finish https://github.com/styled-components/styled-components-website/pull/284 instead. Want to get that up to date and add mobile compatibility instead @el1f?

**Comment by el1f** [comment]
It seems like something I can take up! Will get started on it at some point tomorrow :)

**Comment by el1f** [comment]
Closing this as it seems like its soul now lives in the showcase page :)
