### ISSUE TITLE
Replace badges from badgesize.io

### ISSUE THREAD

**Issue by kitten** [styled-components/styled-components-website#160]
The badges we're including from badgesize.io are currently not served over HTTPS, compromising the site being shown as fully secure.

I'm fairly certain that we can whip something up using https://github.com/siddharthkp/bundlesize instead.

cc @siddharthkp

**Comment by siddharthkp** [comment]
bundlesize only knows about your master branch, not your released version. So there might be a gap there if you don't always publish master

**Comment by philpl** [comment]
@siddharthkp I think that'd be totally acceptable. Otherwise we could add an endpoint that reads the bundle size from unpkg and creates a badge using shields.io

cc @mxstbr

**Comment by siddharthkp** [comment]
> Otherwise we could add an endpoint that reads the bundle size from unpkg and creates a badge using shields.io

Totally can! Don't even need bundlesize™ for that 😄

**Comment by philpl** [comment]
@siddharthkp I guess that's the way to go then 😆

**Comment by chinesedfan** [comment]
Have it already been solved in #173?

**Comment by morajabi** [comment]
@chinesedfan That's probably is right
