### ISSUE TITLE
Remove NextJS section inline snippet and a typo

### ISSUE THREAD

**Issue by morajabi** [styled-components/styled-components-website#162]
https://www.styled-components.com/docs/advanced#nextjs

As our inline snippet exactly matches with NextJS repository why we still have it here? Also there's a type `fro` -> `for`

/cc @mxstbr @philpl

**Comment by philpl** [comment]
On the one hand it’s good for convenience on the other we don’t have to keep it up to date and can just keep linking to the next repo.

I’d be happy if anyone would like to pick this up :)

**Comment by danielzy95** [comment]
Hi! I'd love to help out with this! I'll see what I can do :)

**Comment by danielzy95** [comment]
<img width="1439" alt="screen shot 2017-11-08 at 9 25 13 pm" src="https://user-images.githubusercontent.com/7264984/32586949-5f13da0c-c4cb-11e7-9c92-ee89a5c63014.png">
Is this what you want for the Next.js section? @morajabi @philpl

**Comment by morajabi** [comment]
Thanks, @danielzy95 awesome!  @philpl What do you think about adding a one-paragraph explanation of what they should do? For example:

> Basically you need to add a custom `pages/_document.js` (if you don't have one). Then [copy the logic](https://github.com/zeit/next.js/blob/master/examples/with-styled-components/pages/_document.js) for styled-components to inject the server side rendered styles into the `<head>`. You'll also need to customize the `.babelrc` and use `babel-plugin-styled-components`.

**Comment by philpl** [comment]
@morajabi sounds perfect!

**Comment by danielzy95** [comment]
@morajabi So you'd like me to add that paragraph to the Next.js section?

**Comment by danielzy95** [comment]
@morajabi @philpl  My PR got merged :) I think you can close this issue now
