### ISSUE TITLE
Stringifier problem with [v2] badge on several titles

### ISSUE THREAD

**Issue by morajabi** [styled-components/styled-components-website#165]
There's still an extra dash after links ending with [v2] badge. 
Look at the link in the sidebar and the actual link in the chrome URL bar:
![screen shot 2017-11-06 at 1 23 03 pm](https://user-images.githubusercontent.com/12202757/32435285-bc76097c-c2f5-11e7-8ecd-5ef749e2e979.png)

/cc @philpl

**Comment by philpl** [comment]
Should already be fixed by: https://github.com/styled-components/styled-components-website/pull/164

**Comment by morajabi** [comment]
I knew about that, but why don't we release a new version?

**Comment by philpl** [comment]
@morajabi haha I haven't gotten to it yet, sorry. I'll do so in a few minutes

**Comment by morajabi** [comment]
No worries! Just don't close these until it's REALLY fixed. These are good reminders :)

**Comment by philpl** [comment]
@morajabi It depends on what you refer to as fixed :wink: So I usually close issues when they're fixed on `master`, regardless of whether they're live or not. The same goes for packages for example.

This would be great to be accompanied by auto-deployment, which we don't have yet, but I still prefer to just deploy every now and then, and to close issues when they're done, as in no more code needs to be changed.

**Comment by morajabi** [comment]
@philpl You're right and I see what's your point but at the end of the day, an issue is solved when the end user does not encounter it anymore. 😉 When we haven't deployed, the issue is still out there no matter it is fixed in the code.
