### ISSUE TITLE
Wall of Love

### ISSUE THREAD

**Issue by mxstbr** [styled-components/styled-components-website#17]
A list of all the positive tweets about styled-components! A tiny list compiled here: https://github.com/styled-components/styled-components.github.io/issues/3

**Comment by alfonsogoberjr** [comment]
Hey, I'm working on a PR for this, but I have a question: What route path should this use? 

Going with `/wall-of-love` until/unless something else is specified.

Cheers

**Comment by mxstbr** [comment]
That sounds great to me, can't wait to have this done! Thanks!
