### ISSUE TITLE
Fix meta tags

### ISSUE THREAD

**Issue by mxstbr** [styled-components/styled-components-website#18]
- [ ] Should use a [Twitter summary card with large image](https://dev.twitter.com/cards/types/summary-large-image) and use something like the logo on the gradient background as the image. This is what it currently looks like when tweeted, as tested with the [official validator](https://cards-dev.twitter.com/validator): ![screen shot 2017-05-22 at 19 35 27](https://cloud.githubusercontent.com/assets/7525670/26321289/7dcd1448-3f26-11e7-9e11-3fe2b8f58274.png)

- [ ] Should have a proper description and title on every page

**Comment by mxstbr** [comment]
I made a meta image for us to use:

![styled-components-meta](https://cloud.githubusercontent.com/assets/7525670/26322693/6285c954-3f2c-11e7-83e9-c779c5ff476e.png)

**Comment by philpl** [comment]
I updated it but something seems wrong with the validator. Not even https://styled-components.com's image shows up :/

**Comment by mxstbr** [comment]
We definitely want to fix it for Twitter, that showing up correctly is huge. I'm unsure if the validator is broken or not, let's keep this open and check tomorrow?

**Comment by philpl** [comment]
Ah, alright. I'll do some investigation later :)

**Comment by mxstbr** [comment]
We need some special metatags, that's why I opened the issue initially. Did you add those?

**Comment by philpl** [comment]
Yep, they look correct to me :/ but the image doesn't want to show up

**Comment by philpl** [comment]
The twitter:image:src tag is now pointing to styled-components.com, so it'll work, once this site is deployed and aliased to the real domain :)
