### ISSUE TITLE
Add note about typing props to TypeScript doc

### ISSUE THREAD

**Issue by mxstbr** [styled-components/styled-components-website#183]
Based on https://github.com/styled-components/styled-components/issues/565#issuecomment-287535650

**Comment by simplywondrous** [comment]
I can do this one :)

**Comment by simplywondrous** [comment]
Looks like #565 was a request for documentation / clarity since Typescript didn't yet support generic tagged template literals. They now do with #microsoft/TypeScript#23430 - is documentation clarification still necessary?

**Comment by breadadams** [comment]
From what I can see on https://styled-components.com/docs/api#typescript I think this issue can be closed now?

**Comment by probablyup** [comment]
Yes I think so, thanks @breadadams
