### ISSUE TITLE
Add Patreon logo to homepage

### ISSUE THREAD

**Issue by mxstbr** [styled-components/styled-components-website#184]
patreon.com appears to be entirely built with styled-components! :tada: 

Source and link to brand assets: https://mobile.twitter.com/jbyttow/status/941824755694313473

**Comment by JamesJefferyUK** [comment]
On it

**Comment by mxstbr** [comment]
Awesome!

**Comment by morajabi** [comment]
@JamesJefferyUK Can you please give me the logo to optimize the SVG for you and then you can add it?

**Comment by JamesJefferyUK** [comment]
@morajabi sure I got them from their site: https://www.patreon.com/brand/downloads

**Comment by morajabi** [comment]
@JamesJefferyUK Use https://jakearchibald.github.io/svgomg/ and play with options, then copy the code and include it in the logos file.

**Comment by che-perez** [comment]
@mxstbr is this issue still open for grabs? if so I took the liberty to add the logo to my local repo and this is how it looks...
<img width="1401" alt="patreon logo screenshot" src="https://user-images.githubusercontent.com/23219022/38149699-950e4d72-3429-11e8-8b04-d7d6f72ef29e.png">

**Comment by mxstbr** [comment]
Yes! PR?

**Comment by probablyup** [comment]
Closed via https://github.com/styled-components/styled-components-website/pull/250
