### ISSUE TITLE
Move alternative installation instructions to website

### ISSUE THREAD

**Issue by mxstbr** [styled-components/styled-components-website#185]
The [alternative installation instructions](https://github.com/styled-components/styled-components#alternative-installation-methods) from the main README should really live on the website instead.

Somebody should move them over!

**Comment by JamesJefferyUK** [comment]
I'll take this one 👍

**Comment by SaraVieira** [comment]
<img width="1095" alt="screen shot 2017-12-31 at 00 08 05" src="https://user-images.githubusercontent.com/1051509/34458138-b90d2330-edbe-11e7-8ebf-94b1d641062c.png">

Already added
