### ISSUE TITLE
Add "How can I override styles with higher specificity?" to FAQ

### ISSUE THREAD

**Issue by mxstbr** [styled-components/styled-components-website#187]
Since this question comes up almost every day in the main repo, we should add a FAQ entry to the website.

Based on [this question and answer](https://github.com/styled-components/styled-components/issues/1253#issuecomment-337871693) we should add a note about the `&&&` workaround and why it works to the FAQ.

**Comment by GGAlanSmithee** [comment]
I can take this one

**Comment by GGAlanSmithee** [comment]
Regarding overriding inline CSS, will this trick work too, or will you have to use `!important` in that case? (I can investigate this if needed)

**Comment by mxstbr** [comment]
I think if you use enough ampersands it might work? Not sure though, good question!

**Comment by GGAlanSmithee** [comment]
After a quick glance at google it looks like the most reliable way is to use the `element-attr` CSS Selector in conjunction with `!important`;

```css
div[style] {
   font-size: 12px !important;
   color: blue !important;
}
```

I'll make some tests though, and document both cases in the FAQ section.

**Comment by mxstbr** [comment]
Yep, but adding `!important` to every rule is very annoying, thus the `&&&` hack:

```JS
const Bla = styled.div`
  &&& {
    color: blue;
  }
`
```

This will output the following CSS:

```CSS
.Bla-asdf123.Bla-asdf123.Bla-asdf123 {
  color: blue;
}
```

Which has a high enough specificity to solve the ordering issue. To override inline styles you'll likely have to use `!important`, but imo that's not really what most people have issues with?

**Comment by morajabi** [comment]
The ampersand solution is for overriding styles applied with former classNames or styled applied from the parent and some other cases. It's not meant to be used for overriding inline styles.
```
/* css */
.header {
  background: #453434;
}
```
```
// JSX
<Div className="header sc-wS45d" />

const Div = styled.div`
  && {
    background: white;
  }
`
```

**Comment by GGAlanSmithee** [comment]
@morajabi thanks, that's what I thought. Let's document both cases though, for clarity.

**Comment by justintemps** [comment]
Just to update @morajabi's answer , according to the [docs](https://www.styled-components.com/docs/faqs#how-can-i-override-styles-with-higher-specificity) you need three &s.

So this would be the correct syntax:

```
// JSX
<Div className="header sc-wS45d" />

const Div = styled.div`
  &&& {
    background: white; /* applied */
  }
```

**Comment by mxstbr** [comment]
You can use as many `&` as you want, the more you use the higher the specificity will be!

**Comment by joebentaylor1995** [comment]
Compile error when using more than two `&`s

**Comment by justintemps** [comment]
@joebentaylor1995 can you share an example of a styled component that's failing to compile?

**Comment by alfred-pb** [comment]
Any idea how to do this with createGlobalStyle?
This doesn't work. 
```
export const StyleHtmlColor = createGlobalStyle`
  html {
    && {
      background-color: red;
    }
  }
`;
```

**Comment by Stupidism** [comment]
I had this problem with third-party component libararies with dynamic css injections like `antd`. 

The style tags from `antd` and `styled-components` could be re-ordered according to the js excution order.

![image](https://user-images.githubusercontent.com/5801015/90382226-0c64fe80-e0b1-11ea-99e7-34efb0e11480.png)



And I found the solution in webpack's official document:
```
module.exports = {
  module: {
    rules: [
      {
        test: /\.css$/i,
        use: [
          {
            loader: 'style-loader',
            options: {
              insert: function insertAtTop(element) {
                var parent = document.querySelector('head');
                // eslint-disable-next-line no-underscore-dangle
                var lastInsertedElement =
                  window._lastElementInsertedByStyleLoader;

                if (!lastInsertedElement) {
                  parent.insertBefore(element, parent.firstChild);
                } else if (lastInsertedElement.nextSibling) {
                  parent.insertBefore(element, lastInsertedElement.nextSibling);
                } else {
                  parent.appendChild(element);
                }

                // eslint-disable-next-line no-underscore-dangle
                window._lastElementInsertedByStyleLoader = element;
              },
            },
          },
          'css-loader',
        ],
      },
    ],
  },
};
Insert styles at top of head tag.
```
