### ISSUE TITLE
Add upgrading guides

### ISSUE THREAD

**Issue by mxstbr** [styled-components/styled-components-website#189]
Looking at our traffic stats, a search for "Upgrading" is our 5th most visited page on the main repo:

<img width="218" alt="screen shot 2017-12-18 at 21 54 49" src="https://user-images.githubusercontent.com/7525670/34127640-2be03328-e43e-11e7-95b1-5da25f026eb5.png">

We should add an upgrading guide for v1 -> v2 to the website, which would contain this information: https://github.com/styled-components/styled-components/releases/tag/v2.0.0 (it's kinda funny because the _actual_ upgrade [is a simple `npm install`](https://medium.com/styled-components/announcing-v2-f01ef3766ac2#933c))

We should also make sure that we can add more upgrading guides in the future, i.e. that it's extensible. (v2 -> v3, v3 -> v4, etc) Maybe we should just post our releases on the website? Is it possible to do that automatically based on the Releases page on GitHub? That'd be awesome for sure...

**Comment by SaraVieira** [comment]
Why adding the : https://github.com/styled-components/styled-components/blob/d2d6be5feafdc116a3429e6b6f71f7718c51a8ba/CHANGELOG.md with some text on the top that tells users how to upgrade ?

**Comment by SaraVieira** [comment]
Using the API show a list of https://github.com/styled-components/styled-components/releases is also possible : https://developer.github.com/v3/repos/releases/#list-releases-for-a-repository

**Comment by mxstbr** [comment]
That second one sounds perfect, since we usually have more "human-readable" patch notes in the GitHub releases.

**Comment by SaraVieira** [comment]
Makes sense :)

Should this be a new page in the header ?

**Comment by mxstbr** [comment]
Don't really know, the header's getting pretty full. Maybe `/docs/releases`? :confused:

**Comment by SaraVieira** [comment]
Looking like this ?

<img width="1312" alt="screen shot 2017-12-20 at 11 51 09" src="https://user-images.githubusercontent.com/1051509/34205884-1d07f1d0-e57c-11e7-85b0-c74ce29bd908.png">

**Comment by mxstbr** [comment]
I guess, though that's kinda weird. Maybe we should just get rid of the "Homepage" link (since the logo links there anyway) and add a "Releases" link at the end after "Ecosystem", that's probably better?

**Comment by SaraVieira** [comment]
<img width="1312" alt="screen shot 2017-12-20 at 11 58 07" src="https://user-images.githubusercontent.com/1051509/34206124-13bee59c-e57d-11e7-86b7-24a79e846286.png">

Better ? :)

**Comment by philpl** [comment]
@SaraVieira Perfect :heart:

**Comment by SaraVieira** [comment]
Awesome ! I will try to get started on this after work today 🤓


If I don't anyone is welcome to pick up this , it already has a good documentation

**Comment by SaraVieira** [comment]
This is what I have so far

<img width="1792" alt="screen shot 2017-12-22 at 22 19 01" src="https://user-images.githubusercontent.com/1051509/34313833-3c53ce9c-e766-11e7-828b-1984fb060710.png">

**Comment by philpl** [comment]
@SaraVieira looking good :) only thing is that who released it is irrelevant to the reader. The version number and date however are vital 😬

**Comment by mxstbr** [comment]
Yeah I'd probably even totally remove the person and make the version number the heading?

**Comment by SaraVieira** [comment]
I know that makes sense but i am sucker for photos 😛 

New version:
![screen shot 2017-12-23 at 21 26 35](https://user-images.githubusercontent.com/1051509/34322739-124a9550-e828-11e7-8981-8d65953d8039.png)

**Comment by SaraVieira** [comment]
They all have the same text because I am having a problem with the md component :(

**Comment by SaraVieira** [comment]
Fixed

**Comment by SaraVieira** [comment]
closed by #198
