### ISSUE TITLE
Example on homepage should be display: inline-block

### ISSUE THREAD

**Issue by mxstbr** [styled-components/styled-components-website#19]
So it doesn't span the whole page unnecessarily:

![screen shot 2017-05-22 at 19 41 02](https://cloud.githubusercontent.com/assets/7525670/26321319/a6e123b0-3f26-11e7-8a3c-9dbdd8cebfb1.png)

On the other hand it might be cool to have a live example on the homepage already so people can start tinkering around?

**Comment by philpl** [comment]
We had a live example on the homepage, but @geelen felt like it took up too much space. Maybe you have a nice compromise? :)

**Comment by philpl** [comment]
Got an idea! What if we put the content in the hero section itself in the editor? SO META

So you'll have the image and buttons in there and can edit the hero itself to try out SC. It doesn't get more fancy than that :P

**Comment by mxstbr** [comment]
That's what the current website represents, even though it's just an image. :wink: The buttons are the actual buttons rendered above. Let's do it!
