### ISSUE TITLE
Integrate Danger and make it post screenshot image diffs

### ISSUE THREAD

**Issue by mxstbr** [styled-components/styled-components-website#194]
We should integrate DangerJS into this repo too (just like we do for the [main repo](https://github.com/styled-components/styled-components/blob/master/dangerfile.js)) and make it post the diff image if our snapshot integration tests failed.

/cc @orta maybe somebody has written a Danger plugin for this already?

**Comment by orta** [comment]
They haven't - was just having a chat about that as someone has built [out a version for Ruby](https://twitter.com/carlostify/status/941273407215276032)

The tricky thing will be uploading assets to render in the issue. On Circle you can throw things into an artifacts dir, but travis I'm not really sure. One of our iOS projects does this by uploading to S3 - https://github.com/ashfurrow/second_curtain

Lots of options

**Comment by mxstbr** [comment]
Oh yeah true, good point—the image diff exists on Travis but how do we get that to display in the issue? 🤔
