### ISSUE TITLE
Update / Improve documentation narrative & content

### ISSUE THREAD

**Issue by philpl** [styled-components/styled-components-website#2]
Most of the content right now is from the—fairly outdated—docs in the styled-components repo.

It'd be great to take the time to think about the sections, narrative, missing content, current content, etc.

**Comment by mxstbr** [comment]
We definitely need a big section about why you would do any of this!

**Comment by philpl** [comment]
@mxstbr Maybe we can rewrite the transcript of your talk here into a short raison d'être? The transcript is already there :P https://pusher.com/sessions/meetup/reactivate-london/from-css-preprocessors-to-styled-components

**Comment by philpl** [comment]
@mxstbr @oliverturner I wrote an initial "Motivation" section, based on the talk at Reactivate. Maybe you guys want to iterate on this? https://github.com/styled-components/styled-components-website/blob/master/components/basics/motivation.js

**Comment by oliverturner** [comment]
I guess the person I'd love to hear from most as far as motivation is concerned is @geelen :)

**Comment by geelen** [comment]
Yeah I should definitely write up a few things, but there's not much chance I'll get to that in the next two weeks, sorry.

As for the homepage, I don't mind the split view with live coding possibilities, but visually it's a bit heavy at the moment. I'd leave the original code snippet photo there for the moment, or pick a demo that's a bit less prominent (maybe a couple of buttons, no white background, etc.)

Love that fkn gradient though! Makes me want a mimosa so bad.

**Comment by philpl** [comment]
@geelen I think you're right about the homepage liveedit example. What about if we use the current styled-component website's code in a simple CodeBlock?

![localhost-3000- 1](https://cloud.githubusercontent.com/assets/2041385/25135228/ab05e5c2-2449-11e7-8bd8-5a739e306beb.png)

**Comment by geelen** [comment]
Yeah that works well

**Comment by mxstbr** [comment]
I feel like the code block should be tighter there, in the sense that there's a lot of wasted black space?

**Comment by philpl** [comment]
@mxstbr True that, I'll change the width of the container on the homepage

**Comment by philpl** [comment]
Let's close this for now in favour of more potential issues in the future :)
