### ISSUE TITLE
Add Babel plugin

### ISSUE THREAD

**Issue by mxstbr** [styled-components/styled-components-website#20]
People will look in the DevTools, see the `x-Asdf123` classnames and be turned off. Let's avoid that by using the Babel plugin.

**Comment by philpl** [comment]
This is not possible, since we have to use the `ssr` option. Eith bundle splitting, like in next, the import order will almost always be different on client and server and thus we need to make sure that we generate consistent componentIds.

**Comment by mxstbr** [comment]
Ohhh right, that's why. My bad!

**Comment by philpl** [comment]
https://github.com/styled-components/babel-plugin-styled-components/issues/44
