### ISSUE TITLE
Differentiated styling for release dates

### ISSUE THREAD

**Issue by mxstbr** [styled-components/styled-components-website#201]
The date in the header in italic on the releases page should be "less important", maybe we can move it below/above the header and/or make it smaller and/or give it a different color?

<img width="975" alt="screen shot 2017-12-30 at 21 16 58" src="https://user-images.githubusercontent.com/7525670/34457086-d1cb116a-eda6-11e7-8cdb-083084b7ec69.png">

**Comment by SaraVieira** [comment]
<img width="630" alt="screen shot 2017-12-30 at 23 46 08" src="https://user-images.githubusercontent.com/1051509/34458033-a3a8eafe-edbb-11e7-9e70-b8e54abfa50a.png">

**Comment by SaraVieira** [comment]
<img width="651" alt="screen shot 2017-12-30 at 23 47 04" src="https://user-images.githubusercontent.com/1051509/34458036-c2b3bd20-edbb-11e7-8c17-ad1a6dd7b766.png">

**Comment by SaraVieira** [comment]
@mxstbr @morajabi I like the first one ? What do you think ?

**Comment by philpl** [comment]
@SaraVieira I think the parantheses are superfluous if we move it below (which is a good idea 😬)

I prefer the first one. If you’ll go with the second, as in no accent colours, then I’d lighten the colour and use the normal font, not mono space 👍

**Comment by SaraVieira** [comment]
<img width="1117" alt="screen shot 2017-12-30 at 23 52 52" src="https://user-images.githubusercontent.com/1051509/34458075-9d7fc0c0-edbc-11e7-9ed6-d4585acf5402.png">


Like this @philpl ?

**Comment by philpl** [comment]
@SaraVieira maybe a slightly larger margin but it’s looking sleek 👍✨

**Comment by SaraVieira** [comment]
Fixed and PR created #203  🎉

**Comment by morajabi** [comment]
Can I ask why the version and the headings have the same styling? It doesn't feel they are nested. Maybe we should add a bg to each release section like this: first one light grey second white, third light grey, and so on. (what is it called in English 😅)

(I like the change here tho Sara)
