### ISSUE TITLE
Missing dot in the first paragraph on the Releases page (+ writing style question)

### ISSUE THREAD

**Issue by morajabi** [styled-components/styled-components-website#204]
> Updating styled components is usually just an npm install, only major version might have breaking changes that will be noted in the CHANGELOG

We should add a full stop at the end of the sentence. 

Also, what do you think about making the `CHANGELOG` capital case or lowercase?

**Comment by SaraVieira** [comment]
@morajabi I used to have a quality analyst in my team that kept making me put full stops. 
I have found a replacement for him  🦄

**Comment by mxstbr** [comment]
Yeah, there's also not really a need to link to the changelog on GitHub since the changelog is right below that paragraph. Should probably rephrase to

> Updating styled components is usually as simple as `npm install`. Only major version might have breaking changes, which will be noted in the release notes below.

**Comment by morajabi** [comment]
@SaraVieira Anytime! You can install Grammerly for CFPs or emails to avoid :)
