### ISSUE TITLE
Add FAQ entry about browser support

### ISSUE THREAD

**Issue by mxstbr** [styled-components/styled-components-website#206]
We should add an FAQ entry about "Which browsers does styled-components support?"

The answer is that styled-components supports all the browsers that ReactDOM supports. We should link to the React docs section about this topic (https://reactjs.org/docs/react-dom.html#browser-support), and we should probably explicitly mention that ReactDOM currently supports "IE9+", i.e. any browser and version that was released since (and including) IE9.

**I'd love for this to be picked up by somebody who's never contributed to styled-components or the website before.**

For inspiration on how to tackle this, see this PR by GGAlanSmithee where he added a small FAQ entry: #199 Your PR should touch the same files and add a new entry at the bottom of the FAQ about the browser support topic.

If you have any questions or get stuck along the way, feel free to ask here or to ping me on Twitter! :pray:

**Comment by morajabi** [comment]
> I'd love for this to be picked up by somebody who's never contributed to styled-components or the website before.

One question, do you recommend me to help one of my friends who is just learning HTML and CSS to tackle this? 

If anyone wants to tackle this don't hesitate plz :)

**Comment by mxstbr** [comment]
Probably not depending on their skill level, but maybe you can walk them through it?

**Comment by morajabi** [comment]
Yes, I meant walk them through, would that be helpful or harmful? I guess it might make them familiar w/ how Github works.

**Comment by andrwsalcdo** [comment]
I can try to tackle this if it's still available?
