### ISSUE TITLE
Typescript section and React Native

### ISSUE THREAD

**Issue by yordis** [styled-components/styled-components-website#216]
Related to https://www.styled-components.com/docs/api#typescript

The next code snipper wouldn't work for `react-native`

```js
// styled-components.ts

// notice that I actually import styledComponents from native (not the web one)
import * as styledComponents from 'styled-components/native';
import { ThemedStyledComponentsModule } from 'styled-components';

import ThemeInterface from './theme';

const {
  default: styled,
  css,
  injectGlobal,
  keyframes, // this does not exists on native
  ThemeProvider
} = styledComponents as ThemedStyledComponentsModule<ThemeInterface>;

export { css, injectGlobal, keyframes, ThemeProvider };
export default styled;
```

because I actually use `styled-components/native` I can't use the code snippet.

Looking into the code this will require to fix the typespec for `ThemedStyledComponentsModule` of the native version

**Comment by philpl** [comment]
cc @styled-components/typers

**Comment by swissmanu** [comment]
the current typings for the `react-native` part do not work at all when you want to apply themes.
is this already in work? will have a look otherwise.

**Comment by elnygren** [comment]
@yordis @swissmanu @duro I had some success by adding Themed* versions of interfaces for RN:
https://github.com/styled-components/styled-components/pull/1954

Cheers!

**Comment by bsunderhus** [comment]
Is this still an unsolved thing? I'm trying to use `styled-components/native` but there's no typings for it

**Comment by probablyup** [comment]
Make a request on definitelytyped!

**Comment by nhuesmann** [comment]
@bsunderhus There's an open PR for adding typings for `styled-components/native` here: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/29795#issuecomment-461179361
