### ISSUE TITLE
Basics -> Installation

### ISSUE THREAD

**Issue by mxstbr** [styled-components/styled-components-website#22]
Above "Getting started", instead of the "Motivation" section-that should really be its own section? /cc @philpl

**Comment by philpl** [comment]
I don't know if we need an entire section for "Motivation" given that it's just going to be a video for now. In the future we can write an entire section including the best practices, philosophy, etc.

But yea, let's add a quick installation section

**Comment by mxstbr** [comment]
Yeah that can be a future thing
