### ISSUE TITLE
Releases page is missing

### ISSUE THREAD

**Issue by taneba** [styled-components/styled-components-website#242]
I accessed following url but it shows an error page(An unexpected error has occurred.).
https://www.styled-components.com/releases

Is this already known issue?

**Comment by mxstbr** [comment]
Works for me?

**Comment by taneba** [comment]
oops, it works correctly now.
It may have been a temporary bug 🤔

**Comment by mxstbr** [comment]
🤔 

I'll keep an eye out for that, thanks for pinging us!
