### ISSUE TITLE
Add some docs & examples of the new test utils

### ISSUE THREAD

**Issue by probablyup** [styled-components/styled-components-website#254]
Added in this PR: https://github.com/styled-components/styled-components/pull/1652

**Comment by rfbotto** [comment]
Hi @probablyup, i was about to tackle this issue, but just noticed that this information was already added to the [docs](https://www.styled-components.com/docs/api#test-utilities) in https://github.com/styled-components/styled-components-website/commit/f1fa8716b7b8b4e5bbde04dc01dd23570ca3bd28.

Should this issue be closed, or did you have something else in mind?
