### ISSUE TITLE
Showcase a complex component built with styled-components

### ISSUE THREAD

**Issue by mxstbr** [styled-components/styled-components-website#259]
Questions like this keep coming up:

> “I come from importing stylesheets directly into components. Am I right that styled-component methodology is basically have a styled wrapper that encapsulates a "naked" component to give it styles? But then what if that component is now a component class?”

This happens because our docs mostly only showcase this kind of styled-components usage:

```JS
const Button = styled.button`
  color: blue;
`
```

but they never show how those small components then tie a bigger component together, i.e. it's not immediately clear how to build something like this with styled-components:

```JS
class Counter extends React.Component {
  state = {/* ... */}
  increment = () => {/* ... */}
  decrement = () => {/* ... */}
  render() {
    return (
      <>
        <p className={styles.paragraph}>{this.state.count}</p>
        <button className={styles.button} onClick={this.increment}>+</button>
        <button className={styles.button} onClick={this.decrement}>-</button>
      </>
    )
  }
}
```

For experienced s-c users it's obvious that you'd do something like this:

```JS
const Paragraph = styled.p`/* ... */`
const Button = styled.button`/* ... */`

class Counter extends React.Component {
  state = {/* ... */}
  increment = () => {/* ... */}
  decrement = () => {/* ... */}
  render() {
    return (
      <>
        <Paragraph>{this.state.count}</Paragraph>
        <Button>+</Button>
        <Button>-</Button>
      </>
    )
  }
}
```

But that's totally not obvious for newcomers to the library after just reading the docs. We should showcase this somewhere in our getting started instructions or something like that.

**Comment by kitten** [comment]
@mxstbr Can be closed considering that you also created #260? Maybe we can also follow this up with an FAQ?

@varjmes I believe these issues all come from your Twitter thread with @mxstbr? Thank you so much for asking these questions publicly! I want to underline how important this is. In this particular case we've explained this a couple of times, same questions, same answers. We might've even promised to add it to the docs at some point? But in general, we really need this kind of feedback loop more often. Cheers! And also thanks to you, @oliverturner for jumping in and submitting this PR in record time :heart:

**Comment by mxstbr** [comment]
Yep! :pray:

Thanks @oliverturner you're the best!

**Comment by varjmes** [comment]
Thanks for helping me!
