### ISSUE TITLE
Explain the thinking behind the recommended usage

### ISSUE THREAD

**Issue by mxstbr** [styled-components/styled-components-website#260]
I see this pattern used way too often in the wild:

```JS
class Complex extends React.Component {
  render() {
    return (
      <div className={this.props.className}>
        <p>Why dont you <a>click here</a></p>
      </div>
    )
  }
}

export default styled(Complex)`
  color: blue;
  
  // even worse they add nesting here
  p {
    background: red;
  }
  a {
    text-decoration: underline;
  }
`
```

We should explain why this is much less preferable than the recommended pattern of creating individual components like so:

```JS
const Wrapper = styled.div``
const Paragraph = styled.p``
const Link = styled.a``

class Complex extends React.Component {
  render() {
    return (
      <Wrapper>
        <Paragraph>Why dont you <Link>click here</Link></Paragraph>
      </Wrapper>
    )
  }
}

export default Complex;
```

Which is because

> “By making each of those elements a styled component you can individually adjust their styles. It works to wrap the whole thing in styled(Component), but it locks you into only ever styling one of those DOM nodes.”

**Comment by kitten** [comment]
Same, I think #261 is an awesome start. Maybe we'd just like to clarify there that it's better to keep StyledComponents where we'd normally use elements?

I'd also add to the explanation that we not only swap out elements for StyledComponents _first_ for maintainability and to prevent lock-in, but from another perspective we're making the most minimal change possible (when thinking of abstractions on a single DOM node) which will make the resulting styling just as easy to understand as the change is simple.

**Comment by alaskaa** [comment]
Do you still need some help with this issue? :) or has it been worked on as part of issue #261 ?
