### ISSUE TITLE
Do we still want the search? Algolia gave us 10 days

### ISSUE THREAD

**Issue by morajabi** [styled-components/styled-components-website#271]
> Hi Mohammad,
>
> It seems DocSearch is not used anymore on your website. At least, it had 0 searches in the last month. Do you need help in order to integrate it? Do you still want to keep it?
>
> Please note, that DocSearch is a community project and associated resources are limited, so without answer from you within 10 days, your DocSearch crawler will be disabled.
>
> Looking forward to hearing back from you soon,
>
> Have a great day,
>
> Sylvain Pace
> Software Engineer 
> www.algolia.com |  @algolia

This is from Algolia on 21, June. What we're gonna do? :)

**Comment by probablyup** [comment]
Yeah we definitely want it - need to get https://github.com/styled-components/styled-components-website/pull/158 mergeable.

**Comment by s-pace** [comment]
Happy to help if needed
