### ISSUE TITLE
Doc issue: missing section title

### ISSUE THREAD

**Issue by x3388638** [styled-components/styled-components-website#274]
The title of doc section `Basics > Coming from css` is disappeared.
https://www.styled-components.com/docs/basics#coming-from-css

as the screenshot:
![](https://i.imgur.com/ddXcE4c.png)

I think the source code is [here](https://github.com/styled-components/styled-components-website/blob/master/sections/basics/coming-from-css.js#L4), but I have no idea how to fix to contribute.

**Comment by jmiazga** [comment]
I noticed that too on the site, but when I was running locally it works fine. Im not sure whats deployed vs whats latest in master.

**Comment by probablyup** [comment]
Master hasn’t been deployed in a while. I’ll do it today if I have time.

**Comment by jmiazga** [comment]
@probablyup Do you want to walk me through deploys to potentially offload it in the future?

**Comment by probablyup** [comment]
It requires certain org permissions at the moment, so not something we can
easily offload.

We are looking into the new Now + GitHub integration though to automate the
whole process.

**Comment by probablyup** [comment]
Just deployed, should be good now.
