### ISSUE TITLE
Anchors don't have unique ids

### ISSUE THREAD

**Issue by jmiazga** [styled-components/styled-components-website#282]
There are a few spots on the site where multiple anchors have the same id. One example is here: https://www.styled-components.com/releases#v3.2.0_misc

Within the v3.2.0 release notes there are 3 sections called 'Misc' which have ids of 'v3.2.0_misc'.

This break navigation and also causes accessibility tools to report it as an error.

This issue can also be seen here: https://www.styled-components.com/docs/tooling#installation

**Comment by morajabi** [comment]
@jmiazga Oh, good catch! Are you willing to open a PR yourself? That'd be great! 😃

**Comment by jmiazga** [comment]
What do you recommend? Nesting deeper? so https://www.styled-components.com/releases#v3.2.0_refactors_misc

**Comment by kitten** [comment]
@jmiazga yep, I think the correct behaviour would be to assemble the fully nested ID 🙌

**Comment by jmiazga** [comment]
I'm not sure if it will be an easy fix. I did a little digging into ```commonmark-react-renderer``` and our ```Heading``` renderer. The only info we have is the level and children. For example, when it goes to render the 'Misc' headers for v3.2.0 the data passed into the Heading renderer looks like:

```
{ 
  level: 3,
  children: [ 'Misc.' ]
}
```

There is no other info to tie into except the release version number (which is the current implementation).

I guess it makes sense because technically the headers aren't nested they are siblings of each other.

**Comment by morajabi** [comment]
I think you can also use https://www.npmjs.com/package/shortid for nested headings too
