### ISSUE TITLE
Move website to main repo when finished

### ISSUE THREAD

**Issue by mxstbr** [styled-components/styled-components-website#3]
I'd hate for the docs to be outdated because you can't update the docs and code at the same time. I'd prefer the website (when finished) to live in the same repo as the code if at all possible!

**Comment by philpl** [comment]
Since we have an issue tracking this now I changed the repo's description :)

> The future styled-components website and docs ~(Will live in Lerna monorepo eventually)~

**Comment by imbhargav5** [comment]
How do we go about this? Are we planning to do this now?

**Comment by probablyup** [comment]
Hmm well there is the PR to make a monorepo...

**Comment by mxstbr** [comment]
Yeah—we should still do this once we have the monorepo so that updating the docs can happen at the same time as changing the code.

**Comment by el1f** [comment]
Hey @mxstbr! I started doing some issue cleanup. Is this still something that we want to do at some point?

**Comment by mxstbr** [comment]
I mean, we have the monorepo now so 🤷 might as well? It would definitely make it easier to update code & docs in one swoop...
