### ISSUE TITLE
Don't runtime render markdown on /releases and /ecosystem

### ISSUE THREAD

**Issue by mxstbr** [styled-components/styled-components-website#304]
After #300 the only pages doing runtime markdown stuff are `/releases` and `/ecosystem`.

That means everything else loads quicker due to not loading commonmark on almost every page (yay!), but we should figure out a way to not do runtime markdown rendering on `/releases` and `/ecosystem` too.

**Comment by imbhargav5** [comment]
Any pointers on how we can go about it?

**Comment by mxstbr** [comment]
No idea haha
