### ISSUE TITLE
FAQs library-authors rollup advice

### ISSUE THREAD

**Issue by sag1v** [styled-components/styled-components-website#318]
Hi, i think it would be nice to advice the authors to use the [rollup-plugin-peer-deps-external](https://www.npmjs.com/package/rollup-plugin-peer-deps-external) instead of (or in addition to) [adding each `peerDependency`  to the `external` option](https://github.com/styled-components/styled-components-website/blob/master/sections/faqs/library-authors.md#with-rollupjs).  

What do you think?

**Comment by kitten** [comment]
I think that's a great idea! It's already captured in this section: https://www.styled-components.com/docs/faqs#with-rollupjs

So a small addition mentioning this library would be perfect 👏

**Comment by sag1v** [comment]
Yup exactly where i thought it should be added. 
Can I take this PR?
