### ISSUE TITLE
Example on usage of innerRef is broken

### ISSUE THREAD

**Issue by davl3232** [styled-components/styled-components-website#320]
<img width="1792" alt="screen shot 2018-09-16 at 1 28 59 pm" src="https://user-images.githubusercontent.com/4100566/45599632-9e8b9600-b9b4-11e8-80a3-4e18503f98cd.png">
This example should focus the input on mouse enter, but it doesn't and throws the following error instead:

```
Uncaught TypeError: Cannot read property 'focus' of undefined
    at onMouseEnter (eval at z (react-live.es.js:495), <anonymous>:20:132)
    at Object.<anonymous> (react-dom.production.min.js:15)
    at Object.invokeGuardedCallback (react-dom.production.min.js:16)
    at Object.invokeGuardedCallbackAndCatchFirstError (react-dom.production.min.js:16)
    at P (react-dom.production.min.js:20)
    at I (react-dom.production.min.js:22)
    at R (react-dom.production.min.js:22)
    at Array.forEach (<anonymous>)
    at j (react-dom.production.min.js:21)
    at F (react-dom.production.min.js:24)
```

Seems like the obtained ref is undefined, hence this way of using innerRef doesn't work. Maybe it's a styled-components bug itself.

**Comment by sag1v** [comment]
what version are you using?

**Comment by davl3232** [comment]
Seems I forgot to link the url where it happens.

This comes straight from the website at https://www.styled-components.com/docs/api#innerref-prop.

**Comment by sag1v** [comment]
Seems like the website is using v4. 
As mentioned in the note:
>NOTE
The "innerRef" prop was removed in styled-components v4 in favor of the React 16 forwardRef API. Just use the normal ref prop instead.

And we can confirm this by changing `innerRef` to just `ref` to see it works:  
```
<Input
  placeholder="Hover here..."
  ref={x => { this.input = x }}
  onMouseEnter={() => this.input.focus()}
/>
```

Not sure when it was changed.

**Comment by sag1v** [comment]
@kitten @mxstbr  Are we OK with not supporting lower versions then v4 in this example? 
If so, i think we should go through all the breaking changes of v4 and make the appropriate changes in the docs.

**Comment by davl3232** [comment]
styled-components/styled-components#1560

**Comment by davl3232** [comment]
styled-components/styled-components#1560

**Comment by probablyup** [comment]
Yeah we'll just change this example to be non-interactive
