### ISSUE TITLE
manually call sheet.seal() during SSR to avoid memory leaks

### ISSUE THREAD

**Issue by brunorzn** [styled-components/styled-components-website#329]
This is linked to https://github.com/styled-components/styled-components/issues/1624#issuecomment-425391640

To avoid memory leaks, we need to manually call sheep.seal during SSR, if any error has been thrown during rendering.

Here is an example : 
```
const sheet = new ServerStyleSheet();
    try {
      const page = await renderPage((App) => (props) => sheet.collectStyles(<App {...props} />));
      const styleTags = sheet.getStyleElement();
      return {
        assets, data, ...page, styleTags,
      };
    } finally {
      sheet.seal();
    }
  }
```

**Comment by probablyup** [comment]
We can probably do this in core and just rethrow the error instead of having people do this themself. What do you think @mxstbr?

**Comment by mxstbr** [comment]
Oh yeah not a bad idea!

**Comment by kitten** [comment]
@probablyup @mxstbr I actually think we don't need to clone on develop with SSR anymore as all global styling is now gone if I'm not mistaken 🤔

That'd get rid of the issue more elegantly 😍

**Comment by wmertens** [comment]
🤔 	 Hmm, what version is this? S-C 4.1.1 doesn't have `.complete` on `sheet`…

BTW, @brunorzn 	do you also use Colemak? Sheep instead of sheet :)

**Comment by probablyup** [comment]
Ah yeah it's called `sealed` now: https://github.com/styled-components/styled-components/blob/master/src/models/ServerStyleSheet.js#L18

**Comment by wmertens** [comment]
I updated the example and subject. @kitten	not cloning at all would be better of course - afaik there is no way to add global styles any more
