### ISSUE TITLE
Use styled component inside constructor of another one 

### ISSUE THREAD

**Issue by maxsbelt** [styled-components/styled-components-website#33]
I can't find in new documentation site information from this @mxstbr tweet:
https://twitter.com/mxstbr/status/865916488334684160

And there is a question. I can't use ordinary React component inside constructor, so I do something like that: 
```js
export default styled(Item)``
```
Maybe there is more convenient way to makes it happen?

**Comment by mxstbr** [comment]
Does that Item component have a className? Then just put that there!
