### ISSUE TITLE
Many format changes caused by migrating from js to md

### ISSUE THREAD

**Issue by chinesedfan** [styled-components/styled-components-website#334]
By investigating #330, I noticed that https://github.com/styled-components/styled-components-website/commit/9dc8f544ebd4ed5082ae24fdb0cab129177f9dcb changed a lot of sample code formats.

For example, https://www.styled-components.com/docs/tooling#setup, JSON looks like not very well.

<img width="564" alt="2018-09-30 12 27 34" src="https://user-images.githubusercontent.com/1736154/46248122-bef13100-c447-11e8-8b97-84325c2107cd.png">

**Comment by mxstbr** [comment]
Argh I forgot to check that page, my bad!

**Comment by chinesedfan** [comment]
I want to clarify a little more. Not only JSON format are broken, but also code snippets. For example,

![image](https://user-images.githubusercontent.com/1736154/46451280-fead7500-c7c7-11e8-9a7c-5c0b927ccb95.png)

![image](https://user-images.githubusercontent.com/1736154/46451356-724f8200-c7c8-11e8-99f5-f43a1be55521.png)

**Comment by TommyAlmeida** [comment]
> I want to clarify a little more. Not only JSON formats are broken, but also code snippets. For example,
> 
> ![image](https://user-images.githubusercontent.com/1736154/46451280-fead7500-c7c7-11e8-9a7c-5c0b927ccb95.png)
> 
> ![image](https://user-images.githubusercontent.com/1736154/46451356-724f8200-c7c8-11e8-99f5-f43a1be55521.png)

I didn't even notice, i'll fix it today
