### ISSUE TITLE
Make deprecated/old APIs obvious in search results

### ISSUE THREAD

**Issue by mxstbr** [styled-components/styled-components-website#343]
Right now when I search for "global styles" I have no idea what to click on:

<img width="521" alt="screenshot 2018-10-06 at 15 56 57" src="https://user-images.githubusercontent.com/7525670/46572163-7b378380-c981-11e8-925f-d9e2468eb778.png">

We should somehow "mark" old APIs in the search results so you can still find them if they're used in a legacy codebase and you want to know what they are, but it's obvious that they're old.

**Comment by probablyup** [comment]
They’re under previous APIs

**Comment by imbhargav5** [comment]
I tried to style deprecated apis differently, but I couldn't find a way to get Algolia to somehow send us a boolean. I think one option is to just mark them in a json and then compare against it. I can do that. Any other ideas?

**Comment by imbhargav5** [comment]
I added a _[Deprecated]_ prefix to the titles in the `old` section. Once they are indexed by algolia, it should be obvious to people who are searching them. What do you think?

**Comment by TommyAlmeida** [comment]
@imbhargav5 Are you fixing this issue?

**Comment by stevemao** [comment]
https://github.com/styled-components/styled-components-website/pull/356

@imbhargav5 if you write fix [issue number] your pr will link to the issue. Thanks!

**Comment by imbhargav5** [comment]
This is fixed isn't it?

**Comment by probablyup** [comment]
Yup! Thanks for doing that :)
