### ISSUE TITLE
Unable to use website due to CORS problem

### ISSUE THREAD

**Issue by gshilin** [styled-components/styled-components-website#367]
It happens on homepage and on docs too:
![image](https://user-images.githubusercontent.com/354111/47278706-b1a50d80-d5d3-11e8-982f-e62830967a33.png)

**Comment by manpenaloza** [comment]
Just wanted to report this issue as it still seems exist.

<img width="1439" alt="sc-analytics-fetch-issue" src="https://user-images.githubusercontent.com/4241744/49871629-0c5e2700-fe17-11e8-9136-6b1b397d5d52.png">

Maybe that's not even be a CORS issue? Tried some ways to ping this https://sc-micro-analytics.now.sh/ analytics microservice but haven't succeeded. 

So whatever this microservice tracks: should it still work and has it ever had proper CORS settings to work with the styled-components.com domain?

**Comment by manpenaloza** [comment]
ok, I'll go for it.

**Comment by mxstbr** [comment]
Perfect, thank you! :pray:

**Comment by mxstbr** [comment]
Fixed by the amazing @manpenaloza in #401!
