### ISSUE TITLE
Unmentioned breaking change from v3 to v4: withComponent

### ISSUE THREAD

**Issue by asafigan** [styled-components/styled-components-website#369]
I had a sneaky bug when upgrading. I redid my code to use `style(X)` instead of `X.extend`. I thought all was well until I found some edge cases with `withComponent`. Basically `withComponent` replaces the styled component rather than that component's child. So `as` and `withComponent` have different behavior.

I am assuming that this is `withComponent`'s original behavior. I believe that this should have been mentioned in the [migration guide](https://www.styled-components.com/docs/faqs#what-do-i-need-to-do-to-migrate-to-v4). As the migration guide is written now, it seems like you wouldn't get any bugs by just switching to the new api. But if you use `withComponent` you will.

Here is a simple replacement that doesn't involve changing much code:

Change this:
```
const New = Prestyled.extend`
...
`.withComponent(InnerComponent)
```

To this:
```
const New = styled(props => <Prestyled as={InnerComponent} {...props}/>)`
...
`
```

**Comment by probablyup** [comment]
Want to send a PR adding a bullet to the migration guide and recommending use of “as” instead?
