### ISSUE TITLE
Add License and Update dependency

### ISSUE THREAD

**Issue by ooade** [styled-components/styled-components-website#37]
* Add the MIT License file?
* Update Next.js - It's using [2.3.0-alpha1](https://github.com/styled-components/styled-components-website/blob/master/package.json#L17), 2.4.0 is out and it works fine.

I can take these if permitted???

**Comment by mxstbr** [comment]
Sure, please do!

**Comment by ooade** [comment]
@mxstbr which name should be on the license? Yours?

**Comment by philpl** [comment]
@ooade Just put no name or "styled-components team" :)

**Comment by ooade** [comment]
Ok

**Comment by mxstbr** [comment]
I think mine and Glen's are everywhere right now, so put that there. I'd rather have names there since I don't know the legal situation around not having a name there and I really don't want to mess with that :wink:

**Comment by philpl** [comment]
:+1:
