### ISSUE TITLE
Unterminated comment in css freezes site

### ISSUE THREAD

**Issue by adrianhelvik** [styled-components/styled-components-website#375]
## Environment
Chrome 70, on an iMac on styled-components.com.

## Reproduction
Change the style for the Button component like this:

```
const Button = styled.a`
  /*
`

render(
  <div>
    <Button
      href="https://github.com/styled-components/styled-components"
      target="_blank"
      rel="noopener"
      primary
    >
      GitHub
    </Button>

    <Button as={Link} href="/docs" prefetch>
      Documentation
    </Button>
  </div>
)
```

## Steps to reproduce
1. Copy/paste the code above into the editor on the website
2. Try to do anything

## Expected Behavior
It should treat the rest of the styling as a comment.

## Actual Behavior
The browser becomes unresponsive and must be force exited.

**Comment by arjustini** [comment]
i also had another issue when pasting code into the editor on the website

[Untitled document.pdf](https://github.com/styled-components/styled-components-website/files/2559795/Untitled.document.pdf)

**Comment by arjustini** [comment]
i also had another issue when pasting code into the editor on the website
![issue](https://user-images.githubusercontent.com/22434178/48169645-acc1a880-e2b9-11e8-965f-e6022c5817a7.png)
