### ISSUE TITLE
Add documentation about object styles and edge cases

### ISSUE THREAD

**Issue by probablyup** [styled-components/styled-components-website#385]
From https://github.com/styled-components/styled-components/issues/2197

Similar to how `webpack.DefinePlugin` works, we put the given property in verbatim. In the case of a property like `content`, it actually needs the string quotes preserved so they need to be added manually.

```js
styled.div({
  '::before': {
    content: '"hi"',
  }
})
```

**Comment by mxstbr** [comment]
We should add a section on object styles and that it works in general, we don't have one!

It should highlight the basic use case, pseudo-selectors and media queries, and adapting based on props which looks like this:

```JS
styled.div(props => ({
  color: props.color,
}));
```

**Comment by mxstbr** [comment]
Accidentally closed, sorry.
