### ISSUE TITLE
No warnings or up to date docs on ThemedStyledFunction#attrs object with functions deprecation

### ISSUE THREAD

**Issue by OzairP** [styled-components/styled-components-website#387]
`ThemedStyledFunction#attrs` now deprecates passing in objects that have values to resolve prop values. This was published in v4.1.1 *a week ago* with no warning on the site about the deprecation. 

# Section API `StyledComponents#attrs`
https://www.styled-components.com/docs/api#attrs

Table may be misleading and maybe should be removed.
Paragraph should be changed to

> This is a chainable method that attaches some props to a styled component. The first and only argument is an object or a function that returns an object that will be merged into the rest of the component's props.

and the code should be changed to

```js
const Input = styled.input.attrs(props => ({
  type: 'text',
  size: (props.small ? 5 : undefined),
}))`
  border-radius: 3px;
  border: 1px solid palevioletred;
  display: block;
  margin: 0 0 1em;
  padding: ${props => props.padding};

  ::placeholder {
    color: palevioletred;
  }
`
```

# Section "Attaching additional props"

Second paragraph should be changed from

> The .attrs object also takes functions, that receive the props that the component receives. The return value will be merged into the resulting props as well.

to
> The .attrs parameter can either be an object or a function that returns an object that receive the props that the component receives. The return value will be merged into the resulting props as well.

# Deprecation Warning
The doc should also include a warning about deprecation in v4 and removal in v5.

**Comment by probablyup** [comment]
There’s an open PR, just hasn’t been merged yet.
