### ISSUE TITLE
TS examples need an update after 4.1

### ISSUE THREAD

**Issue by JeroenReumkens** [styled-components/styled-components-website#392]
Hi There! 

It looks like the Typescript typings are broken since the upgrade to 4.1. There is an issue over at the @types repo, but I just wanted to make an issue here as well because I have the feeling that it otherwise would be overlooked. 

Please feel free to close this issue if you don't think there should be an issue here. 

The issue I'm referring to is: 
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/30536

Thanks a lot for all the effort!!

**Comment by ralexand56** [comment]
Is there any way to use the css prop with typescript now?

**Comment by Ky6uk** [comment]
So how to use theming with latest updates?

**Comment by Ky6uk** [comment]
Alright I found some kind of the solution here. We can just use [declaration merging](https://www.typescriptlang.org/docs/handbook/declaration-merging.html) and `@types/styled-components` v4.1.4 and up.

1. Create declaration file (I name it `styled.d.ts`)

```ts
// import original module declaration
import 'styled-components';

// and extend it
declare module 'styled-components' {
  export interface DefaultTheme {
    borderRadius: string;

    colors: {
      main: string;
      secondary: string;
    };
  }
}
```

2. Create a theme

```ts
import { DefaultTheme } from 'styled-components';

const theme : DefaultTheme = {
  borderRadius: '5px',

  colors: {
    main: 'cyan',
    secondary: 'magenta'
  }
};

export default theme;
```

3. Just use original module as is

```ts
import styled from 'styled-components';

export const Component = styled.div`
  color: ${props => props.theme.colors.main};
`;
```

**Comment by Ky6uk** [comment]
@probablyup can we update documentation about it in case this is the right solution? I'm not good in writing docs.

**Comment by Ky6uk** [comment]
@Voronar latest typings allow us to not use re-export at all. So this is much more convenient way to import just original module along the codebase.

**Comment by rovansteen** [comment]
@Ky6uk thanks for that solution, had been struggling with this for hours but that's a really elegant way to solve it. 👍

**Comment by therealparmesh** [comment]
@Ky6uk Thank you! This worked like a charm.

**Comment by bwillem** [comment]
I can't seem to get vscode to autocomplete / intellisense my theme properties - anyone able to?

**Comment by cloutiertyler** [comment]
@Ky6uk I'm not able to get your solution to work with `createGlobalStyles`. I'm getting

```
error TS2339: Property 'colors' does not exist on type 'DefaultTheme'
```

only when using the theme inside of `createGlobalStyles`.

**Comment by Ky6uk** [comment]
@cloutiertyler can you provide a code example?

**Comment by cloutiertyler** [comment]
@Ky6uk The issue was that I was using `ts-node` which apparently was unable to pick up the types (but oddly only in some contexts). I switched to `tsc` and had no issues.

**Comment by fabb** [comment]
I modified @Ky6uk's solution and DRYed it by using `typeof`:
```
import 'styled-components';
import { MyTheme } from 'theme'

declare module 'styled-components' {
  export interface DefaultTheme extends MyTheme {}
}
```

```
const theme = {
  borderRadius: '5px',

  colors: {
    main: 'cyan',
    secondary: 'magenta'
  }
};

export type MyTheme = typeof theme
```

**Comment by SethGunnells** [comment]
I'm finding that, using the suggested declaration merging method, props are being reported as type `any`within my styled components. Any clues as to why this might be? (My apologies if this is not the appropriate place to discuss.)

I've included a very simply example.

![image](https://user-images.githubusercontent.com/245822/54875258-94b27780-4dc9-11e9-8e6a-dbf32fb9cec5.png)
![image](https://user-images.githubusercontent.com/245822/54875267-adbb2880-4dc9-11e9-84b5-29ef6d933d75.png)

Tried rolling back to `4.0.3` with the method of exporting a `ThemedStyledComponentsModule` and the props are typed correctly.

**Comment by realfresh** [comment]
I'm finding I can use styled components `4.2.0` and typescript `3.3.4000` without issues when exporting `ThemedStyledComponentsModule`.

It doesn't seem to work following the documentation and exporting `DefaultTheme`. By doesn't work, props is behaving as any with no typing.

**Comment by djma777** [comment]
> @Ky6uk I'm not able to get your solution to work with `createGlobalStyles`. I'm getting
> 
> ```
> error TS2339: Property 'colors' does not exist on type 'DefaultTheme'
> ```
> 
> only when using the theme inside of `createGlobalStyles`.

Had there been a solution to this? I'm getting the same problem. --trying to learn TypeScript with CRA

**Comment by bduffany** [comment]
Can this issue be reopened?

**Comment by bduffany** [comment]
I'm able to get this working using `createGlobalStyle<{theme: ThemeType}>\` ... \`` but this seems cumbersome.

**Comment by gastonmorixe** [comment]
Solved it by upgrading 

` "fork-ts-checker-webpack-plugin": "^4.1.4",  `

and forcing it

```
"resolutions": {
    "fork-ts-checker-webpack-plugin": "^4.1.4"
  }
```

**Comment by LauraBeatris** [comment]
> I modified @Ky6uk's solution and DRYed it by using `typeof`:
> 
> ```
> import 'styled-components';
> import { MyTheme } from 'theme'
> 
> declare module 'styled-components' {
>   export interface DefaultTheme extends MyTheme {}
> }
> ```
> 
> ```
> const theme = {
>   borderRadius: '5px',
> 
>   colors: {
>     main: 'cyan',
>     secondary: 'magenta'
>   }
> };
> 
> export type MyTheme = typeof theme
> ```

Thanks!! That helped me a lot

**Comment by ivoneijr** [comment]
None of the solutions worked well for me.

For internal components it works fine, but I'm still trying to use custom theme insine `GlobalStytles`  without success.

:/

**Comment by t-nunes** [comment]
> None of the solutions worked well for me.
> 
> For internal components, it works fine, but I'm still trying to use custom theme inside `GlobalStytles` without success.
> 
> ```
> C:/projects/iws/tchan/prototype/my-app/src/styles/GlobalStyles.ts
> TypeScript error in C:/projects/iws/tchan/prototype/my-app/src/styles/GlobalStyles.ts(21,48):
> Property 'colors' does not exist on type 'DefaultTheme'.  TS2339
> 
>     19 |   html, body, #root {
>     20 |     height: 100%;
>   > 21 |     background-color: ${(props) => props.theme.colors.background.page};
>        |                                                ^
>     22 |   }
>     23 | `;
>     24 | 
> ```
> 
> :/

just add the tsconfig.json in root folder

```json
{
  "compilerOptions": {
    "baseUrl": "src",
    "target": "es5",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react"
  },
  "include": [
    "src"
  ],
  "files": [
    "src/styles/styled.d.ts"
  ]
}

```

**Comment by Jay-flow** [comment]
> I modified @Ky6uk's solution and DRYed it by using `typeof`:
> 
> ```
> import 'styled-components';
> import { MyTheme } from 'theme'
> 
> declare module 'styled-components' {
>   export interface DefaultTheme extends MyTheme {}
> }
> ```
> 
> ```
> const theme = {
>   borderRadius: '5px',
> 
>   colors: {
>     main: 'cyan',
>     secondary: 'magenta'
>   }
> };
> 
> export type MyTheme = typeof theme
> ```

Thx! It is work for me 👍🏼

**Comment by MakingStuffs** [comment]
For me the simplest solution was to pass my theme's interface as a declaration for `theme` when calling the function:

```
import { createGlobalStyle } from "styled-components";
import { Theme } from "./types";

export default createGlobalStyle<{ theme: Theme }>`
    * {
        box-sizing: inherit;
    }
    
    html {
        box-sizing: border-box;
    }

    body {
        font-family: OleoScript;
        background-color: ${({ theme }) => theme.colors.main.background};
        color: ${({ theme }) => theme.colors.main.text};
    }

    button {
        border-radius: ${({ theme }) => theme.borderRadius.subtle};
    }
`;
```

**Comment by gfadlallah** [comment]
This works for me:

`/src/styles/styled.d.ts`
```ts
import "styled-components";
import { Theme } from "./src/styles/theme";

declare module "styled-components" {
  export interface DefaultTheme extends Theme {}
}
```

`/src/styles/theme.ts`
```ts
export const theme = {
  colors: {
    blue: "blue",
  }
};

export type Theme = typeof theme;
```

`tsconfig.json`:
```
{
  "compilerOptions": {...},
  "include": ["src/**/*"],
  "files": ["src/styles/styled.d.ts"]
}
```
