### ISSUE TITLE
Add more logos to homepage

### ISSUE THREAD

**Issue by mxstbr** [styled-components/styled-components-website#398]
We should add more logos to the homepage of some of the big companies using styled-components!

- Auth0: https://github.com/auth0/cosmos
- BBC: https://github.com/bbc-News/psammead
- Casper: #284
- Moleskine: #284
- AirBnB: #284
- Tinder: #284
- Lego: #275 
- Ticketmaster: #275 
- Typeform: #275 
- Vogue: #275
- Invision: #275

**Comment by GiuMagnani** [comment]
Working on it :+1:

**Comment by mxstbr** [comment]
That's a great first start, where's the PR?!

**Comment by mxstbr** [comment]
Done, thank you so much @GiuMagnani!
