### ISSUE TITLE
Add the MagicLeap logo to the homepage

### ISSUE THREAD

**Issue by mxstbr** [styled-components/styled-components-website#406]
https://mobile.twitter.com/mxstbr/status/943518837709987840

**Comment by EdwardGoomba** [comment]
Hey Max, I could drop that in?

**Comment by mxstbr** [comment]
Yes please!

**Comment by mxstbr** [comment]
Done

**Comment by AgaAgnieszkaBorcz** [comment]
@mxstbr Please could you let me know if your logo can be used commercially? for example stickers? 

We would love to be able to include your logo as part of our inventory but aren’t sure of the restrictions regarding its use for commercial purposes, so we would like to find out what your policy is regarding this and if this would be a possibility?

We do not plan to modify or alter the logo in any way or claim that it is ours. To get a better idea of how we plan to use the logo, please see the following website, as this is very similar to what we plan to do: https://www.stickermule.com/unixstickers.
