### ISSUE TITLE
Attrs documentation providing deprecated information

### ISSUE THREAD

**Issue by Sakarisson** [styled-components/styled-components-website#428]
The main documentation for the `.attrs` chainable method (https://www.styled-components.com/docs/api#attrs) does not provide any information about receiving a function that returns new attrs (`props => newAttrs`). Instead it only explains how to use functions as object-form attrs (`({ someAttr: props => props.someValue })`), which is deprecated.

It would be nice if the documentation would be updated to 

1. make it clear that this method is deprecated and will be removed in a future version and 
2. describe how to use the function `props => newAttrs` method.

Thanks for this awesome library, by the way.

**Comment by probablyup** [comment]
Want to branch off my PR and finish it out? https://github.com/styled-components/styled-components-website/pull/386

Ran out of time, but it's what you're looking for.

**Comment by Sakarisson** [comment]
@probablyup I can make an attempt to fill out some information about the new `attrs` API. However, I would not be qualified to take ownership of the other aspect of your PR.
