### ISSUE TITLE
Sort logos on homepage by website popularity

### ISSUE THREAD

**Issue by mxstbr** [styled-components/styled-components-website#439]
Rather than alphabetically, we should sort the company logos on the homepage by approximate website popularity according to www.similarweb.com (global rank).

**Comment by manpenaloza** [comment]
makes sense!

note: to avoid manual searching/sorting, just saw similarweb.com offers an api to get the data we'd need https://www.similarweb.com/corp/developer/ for sorting properly. it also offers a free api but that one has limitatations.
- 5 Results Per Metric
- 1 Month of Mobile App Data
- 3 Months of Web Traffic Data 
haven't found any info on whether they provide some more extended free api for open source projects. we can find out.

**Comment by mxstbr** [comment]
Sounds great if you want to dig into that! :+1:

**Comment by manpenaloza** [comment]
ok, I've sent a request to similarweb. let's if that's an option to at least automate sorting.
