### ISSUE TITLE
styled-components examples for React Native in expo snack are not working

### ISSUE THREAD

**Issue by Sshetty2** [styled-components/styled-components-website#440]
**Broken Demos:**

https://snack.expo.io/Sk8O7_9og

https://snack.expo.io/@danielmschmidt/styled-components

when attempting to 'run' the code either in the emulator or on my device, an error message is given:

**Device: (78:20) undefined is not an object (evaluating '_native2.default.View')
  Evaluating module://App.js
  Loading module://App.js**

![snack error](https://user-images.githubusercontent.com/28030683/54350249-4b249880-4623-11e9-8803-d324832d4242.JPG)

**Steps to recreate:**

Click the links and try running the demos

**Comment by chris35469** [comment]
Seeing this error as well.

**Comment by satya164** [comment]
For now `import styled from 'style-components'` without the `/native` seems to work. I'll try to fix the issue with `/native`.

**Comment by chris35469** [comment]
Thanks @satya164 `import styled from 'styled-components` worked. 

https://snack.expo.io/@chris35469/c3R5bG

**Comment by yzalvov** [comment]
> For now `import styled from 'style-components'` without the `/native` seems to work. I'll try to fix the issue with `/native`.

@satya164 rather 'style**d**-components' as soon as you don't want copy&pasting folks to guess what's the `An unexpected error occurred: "https://registry.yarnpkg.com/style-components: Not found"` is all about while yarning the package.

**Comment by free4mOriginal** [comment]
Having similar issue trying to load `styled.img`, but `import styled from 'style-components'` doesn't work for me...

**Comment by yzalvov** [comment]
@free4mOriginal I hope then you red my previous comment more carefully. There was a typo. And there was a fix.
