### ISSUE TITLE
`Define a theme interface` documentation doesn't work with macro import

### ISSUE THREAD

**Issue by codepunkt** [styled-components/styled-components-website#449]
#### System
 - OS: Windows 10 - CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
 - Memory: 940.17 MB / 15.64 GB
#### Binaries:
 - Node: 10.15.1 - C:\Program Files\nodejs\node.EXE
 - Yarn: 1.13.0 - ~\AppData\Roaming\npm\yarn.CMD
 - npm: 6.7.0 - C:\Program Files\nodejs\npm.CMD

## Steps to reproduce
- Create `theme.ts` and `styled-components.ts` as described [in the documentation section "Define a theme interface"](https://www.styled-components.com/docs/api#define-a-theme-interface).
- Change the styled-components import in `styled-components.ts` from `styled-components` to `styled-components/macro`

## Expected Behavior
- Developer friendly classnames in development via /macro
- typed `props.theme`

## Actual Behavior
```
./src/style/styled-components.ts
TypeError: Cannot read property 'name' of undefined at Array.map (<anonymous>)
```

**Comment by probablyup** [comment]
Anything we need to do or can I close this?
