### ISSUE TITLE
Website Example Code Broken

### ISSUE THREAD

**Issue by cbravo** [styled-components/styled-components-website#460]
## Steps to reproduce
visit https://www.styled-components.com/docs/basics#attaching-additional-props
## Expected Behavior
the two inputs should be different sizes based on what is written there.
## Actual Behavior
the two inputs are the exact same size and changing values has no effect.

**Comment by adzshaf** [comment]
Hi, can I work on this issue? @mxstbr

**Comment by probablyup** [comment]
Go for it

**Comment by cbravo** [comment]
There is something really wholesome about this whole thread 😄

**Comment by kelsonpw** [comment]
This issue is fixed in my PR.  Just waiting to get it merged.
