### ISSUE TITLE
Potentially inaccurate docs

### ISSUE THREAD

**Issue by nlitwin** [styled-components/styled-components-website#475]
Hello,

I was only able to get vendor prefixes to go away after reading about the `disableVendorPrefixes` option in [this pull request](https://github.com/styled-components/styled-components/pull/2640) and by adding this line:
```html
<StyleSheetManager disableVendorPrefixes>
```

However [the docs](https://github.com/styled-components/styled-components-website/blob/master/sections/api/helpers/style-sheet-manager.md) say to use:

```html
<StyleSheetManager stylisOptions={{ prefix: false }}>
```

Are the docs simply out of date?

**Comment by probablyup** [comment]
Yes they're out of date :) we decided to change the implementation slightly due to feedback from the stylis author. If you wouldn't mind sending a PR to update it that'd be awesome!
