### ISSUE TITLE
Add Eddie Bauer logo to homepage

### ISSUE THREAD

**Issue by mxstbr** [styled-components/styled-components-website#488]
Fully built with s-c: https://www.eddiebauer.com/

**Comment by galvc** [comment]
Hi, can I work on this one? Would love to help

**Comment by mxstbr** [comment]
Please do! Excited for your PR :100:

**Comment by ashishcodes4** [comment]
hey @mxstbr , 
any updates on this one ? 
is this completed or still pending ? I'd like to this up if not completed yet.

**Comment by galvc** [comment]
Working on it

**Comment by ashishcodes4** [comment]
cool!

**Comment by galvc** [comment]
Hello @mxstbr My PR is failing the checks and I was wondering if I could have some help on how to fix it
This is the log that points to the problem:

FAIL  .next/static/8_6jsORi3BV1YDOHMgc--/pages/index.js: 253.97KB > maxSize 250KB (gzip)

Thanks a lot!
