### ISSUE TITLE
Add Trulia logo to homepage

### ISSUE THREAD

**Issue by mxstbr** [styled-components/styled-components-website#489]
Fully built with s-c: https://www.trulia.com/

**Comment by idrisakmal** [comment]
Hello @mxstbr ! can you assign this to me?

**Comment by mxstbr** [comment]
You got it, can't wait for your PR! 👍

**Comment by el1f** [comment]
Any word on this yet? Otherwise, I'd be happy to take over :)

**Comment by idrisakmal** [comment]
@el1f pr is closed 😁

**Comment by el1f** [comment]
Oh, nice! Didn't see it linked to the issue :)
Think this is ripe to be closed off then!
