### ISSUE TITLE
Perhaps we can add className also to the example?

### ISSUE THREAD

**Issue by JikkuJose** [styled-components/styled-components-website#49]
Perhaps the key aspect of SC is elegance in splitting style/markup. And since many projects still use old CSS classes that are shared for the whole project, class names will remain for many projects.

The new `.attr` chainable method is awesome for this use case & I think adding a `className` in the provided example may be a good idea. Something like

```
import styled from 'styled-components';

const Input = styled.input.attrs({
  type: 'text',
  size: props => props.small ? 3 : 8,
  className: 'pa4 ba bg--black-80',
})`
  background: palevioletred;
  border-radius: 3px;
  border: none;
  color: white;
  padding: ${props => props.padding}
`;
```

**Comment by mxstbr** [comment]
I like it! Maybe a new section under FAQ "Using styled-components with CSS frameworks" and another one to showcase how to use it with react-router etc. like "Using styled-components with react-router"? That's what folks are most likely to google, 

PRs very welcome!

**Comment by JikkuJose** [comment]
Cool, have submitted a PR!
