### ISSUE TITLE
Add Google logo to homepage

### ISSUE THREAD

**Issue by mxstbr** [styled-components/styled-components-website#493]
A lil' cheeky but they used it for a project: https://localopportunity.withgoogle.com/ https://mobile.twitter.com/TomHoad/status/1176399894174740480

**Comment by justinjunodev** [comment]
@mxstbr could you assign this to me? I'd love to help and have been a long time user of SC. 💅💅💅

**Comment by mxstbr** [comment]
Sounds great, go ahead @justinjunodev! 👍

**Comment by justinjunodev** [comment]
PR has been created. Let me know if there are any issues. If you'd like me to tackle any others, don't hesitate to assign them to me. I know there are several. Thanks for the opportunity. 👍

**Comment by mxstbr** [comment]
Feel free to tackle any that are unassigned, that would be awesome!! 👍

**Comment by mxstbr** [comment]
Done!
