### ISSUE TITLE
Add Revolut logo to homepage

### ISSUE THREAD

**Issue by mxstbr** [styled-components/styled-components-website#494]
Revolut.com is using s-c, see https://mobile.twitter.com/RIP212/status/1176458503709503488

**Comment by gabrielaraujof** [comment]
@mxstbr May I try this one?

**Comment by mxstbr** [comment]
Yes please! :fire:

**Comment by ashishcodes4** [comment]
@mxstbr if this is not completed yet, I would want to complete this!

**Comment by omegaspn** [comment]
I want to contribute this, please assign to me

**Comment by el1f** [comment]
@ashishcodes4 @gabrielaraujof were you able to make any progress on this?

**Comment by omegaspn** [comment]
This is my pull request https://github.com/styled-components/styled-components-website/pull/538/files thanks!

**Comment by reececasey** [comment]
@mxstbr This issue seems to be stuck since the new manifest changes are not in the PR. Is it still required?

**Comment by el1f** [comment]
Definitely needed. Feel free to try your hand at it :)

**Comment by reececasey** [comment]
Thanks @el1f 

First PR here: https://github.com/styled-components/styled-components-website/pull/647

Let me know if I have missed anything.  I also noticed one of the showcase images is far too big in file size. Can I raise a PR or do I need to raise an issue?

**Comment by el1f** [comment]
You can go ahead and go with a PR directly as long as you detail what the PR is for so that anyone has the context to get it's purpose :D

**Comment by reececasey** [comment]
@el1f thanks, PR raised for the discussed additional.
