### ISSUE TITLE
Document useTheme hook (v5)

### ISSUE THREAD

**Issue by mxstbr** [styled-components/styled-components-website#503]
Reference PR: https://github.com/styled-components/styled-components/pull/2765

Should go in the API section and maybe be used in the `theming` section!

**Comment by apollonian** [comment]
I can help with this one, @mxstbr! ⚡️

**Comment by O45** [comment]
https://github.com/styled-components/styled-components-website/pull/230#issuecomment-364654261

**Comment by yakovleva-tanya** [comment]
Hi @mxstbr, I'm looking for a good first issue and would like to contribute to this one if it's still available!
