### ISSUE TITLE
FAQ links don't point to the right sections.

### ISSUE THREAD

**Issue by joshwcomeau** [styled-components/styled-components-website#53]
The FAQ links "Support for nesting" and "Referring to other components" take you to the FAQ, but they don't jump to the appropriate section:

https://www.styled-components.com/docs/faqs#referring-to-other-components

This is because the `<SectionLayout>` title doesn't match; the FAQ item headings are all question-format, but it looks like it just uses the dash-case version of the menu item for the hash anchor links.

A fancy solution could be to update `docs.json` to support a "display" heading as well as a "hash" string, for navigation. More simply, we could just update the links to match.

**Comment by mxstbr** [comment]
Let's just update the links to match? I don't know why they should differ anyway? /cc @philpl

**Comment by geoffdavis92** [comment]
@mxstbr @philpl I could take a look at this.

**Comment by philpl** [comment]
@geoffdavis92 Sorry, I think this was already fixed in a past PR :wink:
