### ISSUE TITLE
Add more sites to the showcase page

### ISSUE THREAD

**Issue by el1f** [styled-components/styled-components-website#530]
Now that we have a showcase page we should add more content to it.
Let's decide on a list of websites to add and implement the required changes.

IMO we should also have a CTA inviting visitors to create a PR to add their own website or some website they know uses s-c to the page.

**Comment by mxstbr** [comment]
Let's take the top 10 (?) websites by rank from the company logos (https://github.com/styled-components/styled-components-website/pull/532) and add them!

**Comment by el1f** [comment]
Do you mean to replace the list that's currently in the manifest with the top 10 websites or do you mean to add those that aren't currently in the list while leaving those that re already in

**Comment by mxstbr** [comment]
>  add those that aren't currently in the list while leaving those that re already in

No need to undo all the work that was already done, those are already great!

**Comment by johnxie** [comment]
Can we have [Taskade](https://taskade.com) included in https://styled-components.com/showcase ?

We also have a templates gallery page at https://taskade.com/templates

Our team: https://github.com/taskade

**Comment by el1f** [comment]
Sure! Feel free to open a PR to add it @johnxie :)
You just need to add it in the `companies-manifest.json` file.
