### ISSUE TITLE
Combine the showcase and companies manifest

### ISSUE THREAD

**Issue by el1f** [styled-components/styled-components-website#533]
The two manifest files have so much in common that it makes sense to join them together into a single manifest file. This would also make it easier to maintain them by reducing the degree of redundancy.

**Comment by el1f** [comment]
So, this is actually starting to show a larger degree of nuance than expected.
`showcase-manifest` maps the projects based on a string that represents the name of the project that's being showcased while `companies-manifest` is just an array of companies that makes it simpler to use and sort based on the similarWeb ranking.

The two data structures are not that streamlined and while thinking about how to tackle their union I realized that we may have started from the wrong foothold: those manifests represent two different data entities: `showcase-manifest` is akin to a "projects" data model while the `companies-manifest` represents the "companies" that use s-c. In a relational sense, we have a one-to-many relationship going from compies towards projects which means that a company that's showcased in the home slider may not have any projects to showcase or may have more than a single project to showcase.

I started approaching the merging by trying to expand the items in the `companies-manifest` by adding a `projects` object that contains objects representing the projects made by that specific company.
Showcase would then regenerate a mapping of all of the projects by joining all of the objects in `companies[companyName].projects` into a single mapping object.

Do you have a better approach to suggest for this issue?

**Comment by mxstbr** [comment]
That makes a ton of sense, thank you for thinking through my (obviously) quickly made comment! 👍
