### ISSUE TITLE
Reconsider the layout of the home page

### ISSUE THREAD

**Issue by el1f** [styled-components/styled-components-website#534]
Most of us know how to install an npm package, not all of us know about the benefits of using a solution like s-c rather than traditional SASS and similar. I think styled-components needs to have the **motivations** sections as one of the first pieces of content shown on the homepage.

**Comment by mxstbr** [comment]
I think that makes sense, I wouldn't mind moving the Motivation section the homepage and deferring the getting started section to the docs!
