### ISSUE TITLE
Now no longer aliases to styled-components.com

### ISSUE THREAD

**Issue by mxstbr** [styled-components/styled-components-website#535]
For some reason deploys on the master branch no longer automatically alias to `www.styled-components.com`. @Timer I think this broke with the recent upgrade to Now v2? Any ideas why that's broken? We have the alias configured in the `now.json`.

**Comment by Timer** [comment]
Hmm, the latest `master` commit seems to have been aliased:
https://github.com/styled-components/styled-components-website/commit/ef1b21dd114fd24456230730b31b8becff0f902c#comments

Can you explain what behavior you're seeing specifically?
