### ISSUE TITLE
Companies slider stutters after a certain amount of time

### ISSUE THREAD

**Issue by el1f** [styled-components/styled-components-website#536]
The companies slider stops scrolling at a certain point and just loops back without showing all the logos. 

Preview of the issue:
https://youtu.be/j05qh7r4PIo

**Comment by Deepam101** [comment]
Should it be the infinite running type without any gaps?

**Comment by mxstbr** [comment]
Yes @Deepam101

**Comment by Deepam101** [comment]
Please review #563 .If found correct please merge.
:)

**Comment by el1f** [comment]
Great Job @Deepam101, now we can get back to adding even more logos guilt-free :)
