### ISSUE TITLE
Add Lyft logo to homepage

### ISSUE THREAD

**Issue by mxstbr** [styled-components/styled-components-website#539]
They use styled-components apparently, I think for lyft.com: https://mobile.twitter.com/ebidel/status/1183765268830359553

We should probably also add `lyft.com` to the company showcase!

**Comment by yakovleva-tanya** [comment]
Hi @mxstbr, can I work on this one?

**Comment by mxstbr** [comment]
Yes pleaes @yakovleva-tanya!
