### ISSUE TITLE
Navbar overflows company name on the showcase page

### ISSUE THREAD

**Issue by yakovleva-tanya** [styled-components/styled-components-website#547]
On the showcase page, on certain screen sizes, the navbar overflows company names and there's no way to scroll down to see it.

Preview the issue here:
![Screen Shot](https://user-images.githubusercontent.com/52566711/66830806-08cb8d00-ef5f-11e9-9443-0757f2f07e6b.png)

**Comment by el1f** [comment]
Thanks @yakovleva-tanya! Will look into it ASAP :)
