### ISSUE TITLE
Add header to showcase page similar to homepage

### ISSUE THREAD

**Issue by mxstbr** [styled-components/styled-components-website#571]
The showcase insert on the homepage has some really nice phrasing:

<img width="1440" alt="Screenshot 2019-11-04 at 11 51 38" src="https://user-images.githubusercontent.com/7525670/68115905-c7912200-fef9-11e9-8a61-baa97ade01ef.png">

We should add some similar text to the dedicated /showcase page that explains what it is, something like:

----

# Showcase

styled-components is used by teams all around the world to create beautiful websites like these:

**Comment by neusaguera** [comment]
![showcase-desktop](https://user-images.githubusercontent.com/40834560/68564035-11da4c00-0482-11ea-880a-e6d7f1a85967.png)
![showcase-mobile](https://user-images.githubusercontent.com/40834560/68564038-11da4c00-0482-11ea-8c3d-322595c42892.png)

Hello! Do you like something like this?

**Comment by mxstbr** [comment]
@neusaguera we probably do not want to copy the same style from the homepage, just the phrasing. We likely want to make this more into an actual page and add a heading "Showcase" and a subtitle/intro paragraph which says the "s-c is used by teams..." thing.

I also really like how the homepage showcase shows the name of the website below the screenshot, we should copy that style too and remove the big heading with the name of the website.

Combined together we'd arrive at something like:

----

# Showcase

styled-components is used by teams all around the world to create beautiful websites like these:

--screenshot--
[Ticketmaster]

----

Does that make sense?

**Comment by neusaguera** [comment]
Hi @mxstbr! what do you think about these screenshots? Do you want to keep the link to the sites?

![styled-showcase-desktop-black](https://user-images.githubusercontent.com/40834560/68725719-eaa28c80-05f1-11ea-9759-98e0b8a02f1c.png)
![styled-showcase-desktop-ocher](https://user-images.githubusercontent.com/40834560/68725720-eaa28c80-05f1-11ea-95af-98b71b0e01c5.png)
![styled-showcase-mbl](https://user-images.githubusercontent.com/40834560/68725736-f2fac780-05f1-11ea-8fcd-47b7089c6209.png)

**Comment by mxstbr** [comment]
This is looking much better! @el1f any feedback?

**Comment by el1f** [comment]
Great work! Is the subtitle using the standard body font size? Also, I'm not a super fan of the balloon for the site name and link. Is it shown on hover like on the homepage? All in all, I'm quite positive about the mobile version but skeptic about the balloon. Can you try to make the desktop version look a little more like the mobile version?

**Comment by neusaguera** [comment]
Hi @mxstbr and @el1f,

The font weight of subtitle was thicker than the standard, in this version I show the same font weight. What do you think about this version? In mobile version of  the button dropdown doesn't work and the menu is fixed, this is correct?

![styled-showcase-desktop-2](https://user-images.githubusercontent.com/40834560/68828080-eac88800-06d6-11ea-9e51-2579dfa3ac8d.png)

**Comment by el1f** [comment]
I like the direction this is going towards @neusaguera. Actually, I'd like to build upon your interpretation to add some extra functionality to the showcase page. Would you mind opening a PR for the layout changes?

**Comment by el1f** [comment]
As this issue has been dormant for a while I decided to try and take a shot at it :)
Here is my proposal for the restructuring of the page. What do you think about it @mxstbr ?

I took inspiration from the next.js showcase and a little from the electron.js apps section. This also proposes the addition of the quick contribution from #573 and a proposal to add categories like in the next.js showcase to allow users to browse the showcase based on their categories of interest.

It also adds an optional description field (won't render for the ones that lack one) and a Github link to incentivize styled-components users who have an OS project to share the repo to the project and possibly get a little extra traffic on their projects.

Awaiting feedback before going ahead with the mobile version and the actual coding.

P.S. It would be interesting to share the mockup assets for the website somewhere to help out anyone who wants to propose visual changes to the website, any idea on where to share the assets to make them easily available?

![Desktop HD](https://user-images.githubusercontent.com/10723208/72065153-da4f1b00-32dd-11ea-83ce-49ea80244443.jpg)

**Comment by mxstbr** [comment]
That's beautiful! Love it :fire: Let's do it!

**Comment by el1f** [comment]
Here are the mobile and landscape mobile variants. These will need to handle more edge cases (looking at you iPhone SE and Co. in the wild) as I've taken advantage of the extra screen real estate available in the 18:9 phones. This is the best-case scenario.
Anything you guys think can be improved? I think I'll start coding it at some point during the week.

**Mobile Portrait**
![mobile portrait](https://user-images.githubusercontent.com/10723208/72089228-f10c6680-330b-11ea-892e-5c6b997aadcb.jpg)

**Mobile Landscape**
![mobile landscape](https://user-images.githubusercontent.com/10723208/72089236-f36ec080-330b-11ea-9417-ca10affb06ba.jpg)
