### ISSUE TITLE
Direct linking into a showcase page results in a 404

### ISSUE THREAD

**Issue by el1f** [styled-components/styled-components-website#575]
**Steps to replicate**

1. go to https://www.styled-components.com/showcase/patreon
2. check out the 404 page

I am not super savvy about next.js so I am still trying to wrap my head around how to solve this. The current way showcase works are by having shallow routing starting from `/showcase`. This results in broken links when you try to directly access the specific website's showcase page.

Edit: this also gets in the way of #572

**Comment by el1f** [comment]
I don't really know how to tackle this one :/ 
My first impetus would be to change the structure of the showcase from `/showcase/{company}` to something like `/showcase?item={company}`. Otherwise, I think I'd have to rework the showcase to make the various company pages into their own page using the next.js file tree

**Comment by mxstbr** [comment]
That sounds perfectly fine to me!
