### ISSUE TITLE
Add framer.com by Framer to showcase

### ISSUE THREAD

**Issue by mxstbr** [styled-components/styled-components-website#584]
##### Company info

**Company name:** Framer

**Company website:** https://framer.com

**Similar web global rank:** 185,723

**Link to company logo:** TBD

##### Project info

**project name:** Homepage

**project link:** https://framer.com

**project screenshot:** TBD

**Comment by ttermechikov** [comment]
Hello! Can I take this one?

**Comment by mxstbr** [comment]
Yes please @ttermechikov!
