### ISSUE TITLE
Add priceline.com by Priceline to showcase

### ISSUE THREAD

**Issue by mxstbr** [styled-components/styled-components-website#585]
##### Company info

**Company name:** Priceline

**Company website:** https://www.priceline.com/

**Similar web global rank:** 1509

**Link to company logo:** TBD

##### Project info

**project name:** Website

**project link:** https://www.priceline.com/

**project screenshot:** TBD

**Comment by theashraf** [comment]
Can I take this one?

**Comment by mxstbr** [comment]
Sure!

**Comment by ttermechikov** [comment]
If this is not completed yet, I would want to complete this!

**Comment by theashraf** [comment]
@ttermechikov yes please go for it
