### ISSUE TITLE
[Request] RSS Feed for Releases page

### ISSUE THREAD

**Issue by mmmeff** [styled-components/styled-components-website#598]
Can we get an RSS feed for the releases page? My team uses Zapier webhooks to notify our team chat channels when new releases drop for our major/most-loved third-party dependencies and we'd love to get styled-components on there.

**Comment by probablyup** [comment]
This sounds fine to me. Maybe there's a nextjs plugin for it or it can be done as an API route?

**Comment by JIVIN0902** [comment]
Hi.
I am new to the open source community and am looking to contribute eagerly.
I would like to be assigned this issue.
Thanks!

**Comment by CharlieWWW94** [comment]
Hi! Is this still available? Would love to take it.

**Comment by angad-sethi** [comment]
Hey folks, I've raised a PR for this [here ](https://github.com/styled-components/styled-components-website/pull/969). Please let me know what you think 🙂 .
@quantizor, I've accounted your [feedback](https://github.com/styled-components/styled-components-website/pull/802#discussion_r757908039) on a previous PR that aimed to add this functionality in 😊.
