### ISSUE TITLE
Add documentation on imports

### ISSUE THREAD

**Issue by philpl** [styled-components/styled-components-website#60]
Just had a brief discussion here: https://github.com/styled-components/styled-components-website/pull/59

So either we:

- Add some notes on imports in "Getting Started"
- Add some notes to each helper in the API section
- Add some notes here and there ( 👎 )
- Add an import functionality to react-live ( any ideas )

cc @TrevorBurnham @mxstbr

**Comment by wachunei** [comment]
I would add a little section just between Installation and Getting Started or after the first paragraph inside Getting Started

# Importing
Import `styled` or helpers such as `css` or `keyframes`
```js 
import styled, { css, keyframes } from 'styled-components';
```

**Comment by geoffdavis92** [comment]
@mxstbr @wachunei Is this still being worked on? If it's still open, I'd love to give this a shot

**Comment by mxstbr** [comment]
See here for some active discussions: #51, PRs welcome!

**Comment by philpl** [comment]
@mxstbr It seems that #51 should solve this completely, so let's focus on that instead and move all discussion to it instead.
