### ISSUE TITLE
Add Stream to the showcase

### ISSUE THREAD

**Issue by mxstbr** [styled-components/styled-components-website#602]
https://getstream.io/

They use styled-components for some parts of their app: https://medium.com/better-programming/styled-components-vs-css-stylesheets-62e3fb690991

**Comment by rafaelbalanquet** [comment]
Hello! My team and I would like to get more information on this issue and are interested in looking into it! Let me know if you can specify exactly what "showcase" piece you would want manipulated. Thanks!
