### ISSUE TITLE
[Showcase] - Next/previous handlers scroll to top behaviour can be improved  

### ISSUE THREAD

**Issue by luisFilipePT** [styled-components/styled-components-website#615]
As requested on twitter @el1f 

## Issue

The new showcase on the homepage is great but when clicking the next or previous handler of the slideshow the scroll always goes back to top which is a bit annoying.
When looking at the showcase sites I see myself clicking the handler, scrolling a bit down, click next, scroll a bit down and so on.

## Suggestion

Disable scroll behaviour on handlers click action.

Reproduced on desktop and mobile

If you want to change this I don’t  mind doing it 🙌 just let me know or assign this issue to me.

Cheers

**Comment by el1f** [comment]
No worries, I already got the PR ready to submit :)
I'm adding another couple tweaks to the page in the same PR before submitting though.
Thanks for the feedback and the help, it's really appreciated 😊
