### ISSUE TITLE
Add SwissDev job board by SwissDev to showcase

### ISSUE THREAD

**Issue by Vrq** [styled-components/styled-components-website#625]
##### Company info

**Company name:** SwissDev Jobs

**Company website:** https://swissdevjobs.ch/

 

**Similar web global rank:** 583,4000 Global Rank

**Link to company logo:** https://static.swissdevjobs.ch/pictures/swissdev-javascript-jobs.svg

##### Project info

**project name:** SwissDev Jobs job board

**project link:** https://swissdevjobs.ch/jobs/JavaScript/All

**project screenshot:** https://static.swissdevjobs.ch/pictures/swissdevjobs-project-screenshoot.png

**Comment by Vrq** [comment]
@5el1f what do you think?

**Comment by Vrq** [comment]
@el1f what do you think? 😃

**Comment by el1f** [comment]
LGTM

I'm quite busy this week so if you're able to, please provide a PR to add the site to the slideshow. Otherwise I'll try and add it as soon as I'm able to :)

**Comment by Vrq** [comment]
@el1f created a PR in: https://github.com/styled-components/styled-components-website/pull/639

Hope I have not missed anything 😄
