### ISSUE TITLE
Document new APIs in v5.1

### ISSUE THREAD

**Issue by probablyup** [styled-components/styled-components-website#629]
https://github.com/styled-components/styled-components/releases/tag/v5.1.0

- `shouldForwardProp` API (web-only)
- transient props API

**Comment by sai-chai** [comment]
I'd like to pick this issue up.

**Comment by el1f** [comment]
Go ahead @sai-chai! Looking forward to your PR :)

**Comment by sai-chai** [comment]
The PR for this ticket is now open.

**Comment by sai-chai** [comment]
I could really use a review of my PR: #644
