### ISSUE TITLE
Add eslint and prettier to repo

### ISSUE THREAD

**Issue by SaraVieira** [styled-components/styled-components-website#63]
Yellow! 

I was thinking maybe adding eslint and prettier would be a good idea here since the website has a lot of components and things can get messy with different ways of writing code

_Sent from my Bq Aquaris M5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by philpl** [comment]
Yep, as discussed, I'll need to set up eslint, prettier, and lint-staged. I'll see when I can find time for this :)

**Comment by SaraVieira** [comment]
@philpl I created the ticket more to see if I can do this ?

**Comment by philpl** [comment]
Sure! I'd be happy to hand this task over to you :)

You just need to copy what's done on the main styled-components repo, so the eslintrc, the related packages, remove the flow stuff from eslintrc, and copy all lint-staged stuff.

Should be straightforward, and if you run into any trouble, I'm here to help :)

**Comment by SaraVieira** [comment]
Can I add stylelint too? 

_Sent from my Bq Aquaris M5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by mxstbr** [comment]
Yes please!

**Comment by SaraVieira** [comment]
@mxstbr I like how you intervene in my comments for positive reinforcement  😝

**Comment by SaraVieira** [comment]
This can be closed 🎉🎉🎉🎉🎉🎉

**Comment by mxstbr** [comment]
Awesome!!!
