### ISSUE TITLE
Add PageXL by Lauyan Software to showcase

### ISSUE THREAD

**Issue by PlanetIrata** [styled-components/styled-components-website#632]
##### Company info

**Company name:** 
Lauyan Software Sarl

**Company website:** 
https://www.lauyan.com

**Similar web global rank:** 
N/A

**Link to company logo:** 
[Square logo](https://pagexl.ams3.digitaloceanspaces.com/logos/PageXL%20Vertical%20Logo%20Color.svg)
[Horizontal logo](https://pagexl.ams3.digitaloceanspaces.com/logos/PageXL%20Horizontal%20Logo%20Color.svg)

##### Project info

**project name:** 
PageXL

**project link:** 
https://pagexl.com

**project screenshot:** 
![screenshot-styled-components-1280x720](https://user-images.githubusercontent.com/1729529/79119496-c90c2380-7d90-11ea-9163-80fd6dffbf7b.png)

**Comment by julva-bat** [comment]
Too much email

**Comment by julva-bat** [comment]
Too much email

**Comment by julva-bat** [comment]
Cvhj

**Comment by PlanetIrata** [comment]
Hi, could you elaborate more on this « Too much mail » message ?

Thx

**Comment by probablyup** [comment]
Ignore it, was a spambot

**Comment by Sankar-Rajendran** [comment]
PR https://github.com/styled-components/styled-components-website/pull/672
