### ISSUE TITLE
Add WazirX Exchange Platform by WazirX to showcase

### ISSUE THREAD

**Issue by anvaynk** [styled-components/styled-components-website#636]
##### Company info

**Company name:**
WazirX

**Company website:**
https://wazirx.com

**Similar web global rank:**
48,011

**Similar web India rank:**
3,099

**Link to company logo:**
https://wazirx.com/logo.png
##### Project info

**project name:**
WazirX Exchange Platform

**project link:**
https://wazirx.com

**project screenshot:**
![image](https://user-images.githubusercontent.com/1617920/79729001-712f6880-830c-11ea-96ae-89044310d554.png)

**Comment by kibuikaCodes** [comment]
Hey. May I take this one?

**Comment by kibuikaCodes** [comment]
Find my pull request here: https://github.com/styled-components/styled-components-website/pull/642
