### ISSUE TITLE
Add Tooling Section

### ISSUE THREAD

**Issue by MicheleBertoli** [styled-components/styled-components-website#64]
We want to create a Tooling section, where we are going to add:
- `babel-plugin-styled-components` (now under Advanced, see: styled-components/styled-components-website/pull/62)
- `jest-styled-components`

**Comment by bhough** [comment]
Would also like to add 'polished` to this as well.

**Comment by SaraVieira** [comment]
Maybe we should also add the stylelint configuration to the section as well

**Comment by mxstbr** [comment]
This is great! We should definitely move the stylelint processor plus the Babel plugin over, opening new issues for that.
