### ISSUE TITLE
Add the League of Legends website by Riot Games to the showcase

### ISSUE THREAD

**Issue by mxstbr** [styled-components/styled-components-website#643]
##### Company info

**Company name:** Riot Games

**Company website:** https://www.riotgames.com/en

**Link to company logo:**

##### Project info

**project name:** League of Legends Website

**project link:** https://leagueoflegends.com

**Similar web global rank:** 1,819 https://www.similarweb.com/website/leagueoflegends.com

**project screenshot (1280x720px):**

**Comment by kibuikaCodes** [comment]
May I take this one?

**Comment by kibuikaCodes** [comment]
@mxstbr Find my pull request here https://github.com/styled-components/styled-components-website/pull/642. It doubles up together with the WazirX issue.

**Comment by Arun4033622** [comment]
Since the above PR became stale, I've made the changes in https://github.com/styled-components/styled-components-website/pull/645

**Comment by kibuikaCodes** [comment]
@Arun4033622 nice work .

**Comment by Arun4033622** [comment]
> @Arun4033622 nice work .

Thank you @kibuikaCodes!
