### ISSUE TITLE
Showcase Page Font

### ISSUE THREAD

**Issue by jordanliu** [styled-components/styled-components-website#651]
![image](https://user-images.githubusercontent.com/9423525/82968934-610a4900-9f9c-11ea-9b2a-1d95cbc2c6ec.png)

Link: https://styled-components.com/showcase

Should the font on this page's body be Times New Roman or is it just a fallback font?

**Comment by el1f** [comment]
It's one of the fallback fonts.

**Comment by jordanliu** [comment]
> It's one of the fallback fonts.

Noted
