### ISSUE TITLE
The link to the equal justice initiative isn't obviously a link

### ISSUE THREAD

**Issue by threepointone** [styled-components/styled-components-website#655]
Thanks for changing the website! I appreciate it. But the hashtag on top, it's not visible it's a link, and there's no feedback when I hover over it, other than the cursor. Please make it obvious with an underline or so that it's a link, or ideally, also add a message separately beside it. Thank you! 

// cc @mxstbr

**Comment by el1f** [comment]
Will tackle this in a couple hours or so ;)

**Comment by mxstbr** [comment]
Pushed a quick fix for this by adding a longer message!

**Comment by el1f** [comment]
Apologies for missing my commitment. Had quite a rough day :/

**Comment by mxstbr** [comment]
No stress at all 💜

**Comment by threepointone** [comment]
Appreciate this, thank you very much.
