### ISSUE TITLE
Automatic vendor prefixing missing docs

### ISSUE THREAD

**Issue by lucianojss** [styled-components/styled-components-website#656]
## Description 

I couldn't find any information relatively how automatic vendor prefixing is being done on the documentation.

After some digging I found that `styled-components` uses [stylis.js](https://github.com/thysultan/stylis.js) for processing css. 

## Solution 

It could be good to add this information in the docs. What you guys think?

**Comment by el1f** [comment]
It is incredible how entitled I've become in the last 4-5 years to the point where I don't even ask myself this question when I start using a library that intermediates me and my style, I just take auto prefixing for granted 😂

Excuse the tangent, it just got me wondering. Where do you think we should put this information? My mind immediately went to the FAQ but I think this specific piece of information lacks the "F" for that. Any suggestions?

**Comment by kitten** [comment]
I’d say this is a good candidate: https://styled-components.com/docs/basics#coming-from-css

I do have to apologise for this missing. The information on this in stylis was ever changing, since it’s based on a lot heuristics and was updated frequently. So keeping a list of prefixes is hard and that list would be very long.
That I think held us back from adding a section on it in general, which should’ve been obvious.

**Comment by lucianojss** [comment]
To be honest I feel that FAQ is the right place.

We could add a new section something like "How automatic vendor prefixing works".
And yes keeping a list of all prefixes can be hard to maintain, so the focus should be just passing the information of how it works and leave a link to a place where the list of prefixes is (if there is such a place I couldn't find in `stylis.js`.

I am more than happy to create my first PR to storybook docs with that info. 😃

**Comment by lucianojss** [comment]
Opened a MR https://github.com/styled-components/styled-components-website/pull/734 to close this issue please feel free to review it 😃
