### ISSUE TITLE
Add kumparan.com to showcase

### ISSUE THREAD

**Issue by mxstbr** [styled-components/styled-components-website#664]
Kumparan.com is a massive newspaper in Indonesia, and the website seems to be fully built with styled-components! :clap:

**Comment by joe-orav** [comment]
Hi, if no one is working on this, I can add the site.

**Comment by joe-orav** [comment]
Here's the pull request: #680

**Comment by jvishad** [comment]
Please assign it to me.Thanks in advance.:)

**Comment by ItzaMi** [comment]
Seems like this issue was already handled with #735 but wasn't closed
