### ISSUE TITLE
Add unrealengine.com to the showcase

### ISSUE THREAD

**Issue by mxstbr** [styled-components/styled-components-website#666]
unrealengine.com the main landing page is fully built with styled-components!! :fire:

**Comment by Sankar-Rajendran** [comment]
Hi @mxstbr I am interested to take up this, but where can we get the logo SVG files, do we need to create one by ourselves?

**Comment by el1f** [comment]
Hello @Sankar-Rajendran! You can find the unreal logo [here](https://www.unrealengine.com/en-US/branding)!
Usually for these bigger companies just searching for "COMPANY NAME brand guidelines" yields official resources for their design and logo work.
Feel free to start a PR for this addition to the showcase!

**Comment by Sankar-Rajendran** [comment]
PR raised https://github.com/styled-components/styled-components-website/pull/672
