### ISSUE TITLE
The "documentation" button is broken

### ISSUE THREAD

**Issue by MicheleBertoli** [styled-components/styled-components-website#67]
Hello, the "documentation" button is broken in production:

<img width="468" alt="screen shot 2017-07-30 at 11 43 44" src="https://user-images.githubusercontent.com/1308971/28752645-7eed7cb0-751c-11e7-8a40-f9d0eca0de4c.png">

The classe names (`sc-brqgnP dlxELr sc-bZQynM coTCuP`) seem to be right, but the order on which they are applied is wrong:

<img width="413" alt="screen shot 2017-07-30 at 11 45 22" src="https://user-images.githubusercontent.com/1308971/28752651-aa99d854-751c-11e7-8401-bd66f7386ea2.png">

I can't repro the issue on dev (master).

**Comment by philpl** [comment]
Weird! If it's gone on master I'll just try to redeploy it

**Comment by SaraVieira** [comment]
@MicheleBertoli @philpl From what I see this is fixed right ?

**Comment by MicheleBertoli** [comment]
Oh yes, I confirm it's fixed.
Thanks @SaraVieira @philpl.
