### ISSUE TITLE
Add Homely to the showcase

### ISSUE THREAD

**Issue by Morganjackson** [styled-components/styled-components-website#673]
##### Company info

**Company name:**

Homely Group Pty Ltd

**Company website:**

https://www.homely.com.au/

**Similar web global rank:**

48,470
https://www.similarweb.com/website/homely.com.au/

**Link to company logo:**

https://www.homely.com.au/media-kit

##### Project info

**project name:**
Homely

**project link:**
Homepage: https://www.homely.com.au/
Listing details: https://www.homely.com.au/homes/67-lansell-road-toorak-vic-3142/6796562

**project screenshot:**

https://drive.google.com/file/d/1-g23FYp3HA44wHkn8IoAg8X8SelHzrx5/view?usp=sharing

**Comment by Sankar-Rajendran** [comment]
PR https://github.com/styled-components/styled-components-website/pull/672
