### ISSUE TITLE
Add section about using styled-components with third-party component libraries

### ISSUE THREAD

**Issue by mxstbr** [styled-components/styled-components-website#7]
Not many people are aware that you can use styled-components with any third-party component library by just doing

```JS
import { Button } from 'component-lib';

const MyButton = styled(Button)`
  styles: here;
`
```

We should add that somewhere in the docs!

**Comment by philpl** [comment]
It's actually already there: https://sc-next-docs.philpl.com/docs/basics#styling-any-components

The section was called "Third-party components" before though, but it was renamed on the `v2` branch to "Styling any components."

**Comment by mxstbr** [comment]
Oh, nice!
