### ISSUE TITLE
IMDb and Spotify are displayed awkwardly 

### ISSUE THREAD

**Issue by brnt-toast** [styled-components/styled-components-website#711]
Both state the word "Website" after the name - ex: Spotify Website | IMDb Website...
Wasn't sure to just fix it or submit an issue

**Comment by fpc97** [comment]
I think it's done on purpose to clarify it's the website and not the app that's being displayed

**Comment by brnt-toast** [comment]
The link in the showcase body clearly states it is a website.  Instead of, "IMDb Website By IMDb  -> Go to website" it could be phrased as "The Internet Movie Database By IMDb -> Go to website". This would also work with Spotify as well. "Spotify By Spotify -> Go to website"

**Comment by ARKEOLOGIST** [comment]
This is solved with #732.
