### ISSUE TITLE
Semantic errors in the Showcase body

### ISSUE THREAD

**Issue by brnt-toast** [styled-components/styled-components-website#715]
There are 3 main tags on the page.  They can be found in the figure element, which is nested below the nav tag in the showcase body div. Semantically there can only be one main tag. It makes sense for the for the screenshot(16:9) in the showcase body which is mostly correct in hierarchy as well. The thumbnails, however, not so much.

**Comment by ARKEOLOGIST** [comment]
This seems to have been solved, I see the main tag as a <div>. Can you please re-check?

**Comment by ARKEOLOGIST** [comment]
This seems to have been solved, I see the main tag as a div tag. Can you please re-check and close this if possible?
