### ISSUE TITLE
Use <code> tag instead of <pre> tag. Translators try translate <pre> tag, but not <code> tag. 

### ISSUE THREAD

**Issue by MaxmaxmaximusAWS** [styled-components/styled-components-website#719]
Use `<code>` tag instead of `<pre>` tag. Translators try translate `<pre>` tag, but not `<code>` tag. I use chrome google translator to Russian and i see:

![image](https://user-images.githubusercontent.com/69426460/91702559-94eba080-eb81-11ea-8437-eda63e9ef659.png)

Its html symantic error =) please wrap all code examples to code tag to increase international availability. And also, it will greatly help blind people, because screen readers are now trying to read the translated javascript code out loud =)

For example, I have a blind programmer friend, she is from Japan and she is always upset when she has to switch the language to English or Japanese, at the moments when the electronic announcer starts reading the randomly translated into Japanese code examples.

I understand that ordinary people do not care about disabled people and foreigners. Yet we are one planet, and we are all human. I would be very grateful to you for this little thing. I am learning English, but so far I cannot understand the documentation without a translator, although your library used in my company and it is beautiful. Thank you for styled-components.

P.S. hello from Russia =)

**Comment by kitten** [comment]
Oh, I believe that's indeed an issue but the correct semantic tag here is to use both, so `<pre><code>`

A PR is welcome but if no PR comes in for it I'll see when I'll get to fixing it soonest 👍

**Comment by shangyilim** [comment]
I would love to start working on this .

**Comment by shangyilim** [comment]
I'll try to work on this issue
