### ISSUE TITLE
FAQ: Why you should to avoid declare styled component in render method

### ISSUE THREAD

**Issue by maxsbelt** [styled-components/styled-components-website#75]
Sometimes I see in different PRs something like that:

```js
const Header = () => {
  const Title = styled.h1`
    font-size: 10px;
  `

  return (
    <div>
      <Title />
    </div>
  )
}
```

As I understand classes for this component will be generated only in runtime in browser and even SSR doesn't help. It's pretty hard to describe this all the time, so it will be great to have a link in official documentation.

**Comment by philpl** [comment]
That's a good idea! Cheers :)

Generally I'm not really sure why some do it like this, even if we explicitly say that it's returning a component, but a specific section on it won't hurt
