### ISSUE TITLE
Offer link to new Discord

### ISSUE THREAD

**Issue by jasonwilliams** [styled-components/styled-components-website#764]
Hi I'm one of the contributors to https://github.com/styled-components/vscode-styled-components over there we've set up a Discord for the Styled Components community.  

As spectrum is being [switched off](https://spectrum.chat/spectrum/general/join-us-on-our-new-journey~e4ca0386-f15c-4ba8-8184-21cf5fa39cf5) this might be a good time to promote this server on the website and have users move there.

Could you add a link to the website?
link is here: https://discord.gg/hfGUrbrxaU

**Comment by probablyup** [comment]
Sounds good to me, want to submit a PR?
