### ISSUE TITLE
Move stylelint processor and config docs to the tooling section

### ISSUE THREAD

**Issue by mxstbr** [styled-components/styled-components-website#78]
Rather than living on GitHub, the docs for the [`stylelint` processor](https://github.com/styled-components/stylelint-processor-styled-components) and the [shared config](https://github.com/styled-components/stylelint-config-styled-components-processor) should all live on the website to improve discoverability.

**Comment by mxstbr** [comment]
Done by @SaraVieira! :tada:

Now we just gotta get rid of the READMEs of the processor and the config :blush:

**Comment by SaraVieira** [comment]
@mxstbr I can do that tomorrow if you want :)

**Comment by mxstbr** [comment]
Awesome!
