### ISSUE TITLE
Add [project] by [company] to showcase

### ISSUE THREAD

**Issue by MaxmaxmaximusAWS** [styled-components/styled-components-website#787]
![image](https://user-images.githubusercontent.com/69426460/121279563-6dc6ba00-c8dd-11eb-983f-38bac264665c.png)

When i hover mouse on this element, title wraps to another line during animation. You need to prevent text wrapping for headings.

**Comment by DarkSoul26** [comment]
I have been trying to resolve this issue for quite some time.
### **Will this kind of view work?**
![image](https://user-images.githubusercontent.com/60578902/130184342-41880ff1-af72-41f8-a561-6c827033e45e.png)
**_The title does wrap to another line but there's no interruption in the animation._**

**Comment by kitten** [comment]
Invalid title; also PRs are welcome 😅
