### ISSUE TITLE
Move Babel plugin documentation to the tooling section

### ISSUE THREAD

**Issue by mxstbr** [styled-components/styled-components-website#79]
Rather than living on GitHub, the docs for the [Babel plugin](https://github.com/styled-components/babel-plugin-styled-components) should live on the website to improve discoverability.

**Comment by philpl** [comment]
It’s already in there and was moved to the tooling section 😬😜

**Comment by mxstbr** [comment]
Really? All of the Babel plugin README? Can we get rid of that and link to the website?

**Comment by philpl** [comment]
@mxstbr This should be all of it? Frankly, it's just about the options so it's not a lot https://www.styled-components.com/docs/advanced#babel-plugin

@SaraVieira's PR for it: https://github.com/styled-components/styled-components-website/pull/62

**Comment by mxstbr** [comment]
Oh wow, let's get rid of the README then! @SaraVieira want to submit a PR to the Babel plugin repo that removes the content from the README and links to the website instead?

**Comment by SaraVieira** [comment]
Sure man ! On it !
