### ISSUE TITLE
Add "Guides" section

### ISSUE THREAD

**Issue by mxstbr** [styled-components/styled-components-website#80]
We could use a more tutorial-like guides section for some longer topics.

- Server-side rendering with Express (including setting up a build process?)
- Setting up a codebase for success (stylelint + prettier + folder structure?)
- Preact + styled-components
- Inferno + styled-components
- Other ideas?

**Comment by philpl** [comment]
I'd love to also mix these up with some Youtube videos or links to other resources. We have some great content on Medium for example, so it'd make sense not to try to replace them, but to complement and integrate them instead :+1:

**Comment by mxstbr** [comment]
Yep, we could host the Guides on Medium and talks on YouTube and then have a "Resources" section? I'm just a bit worried that that'll end up being just like a link dump.

**Comment by SaraVieira** [comment]
@mxstbr @philpl I could do a video with the second one if you guys want , use react-create-app and set it up

**Comment by mxstbr** [comment]
That sounds awesome @SaraVieira!

**Comment by SaraVieira** [comment]
@mxstbr @philpl I have been doing preact screencasts for the last couple of days so you can get a sense of how I do them you can see them here:
https://www.youtube.com/playlist?list=PL1O2bxLvC8EPw09PKUl3smGrujiZbQFG9

Not public yet but json already approved them 🎉
