### ISSUE TITLE
Improve SEO

### ISSUE THREAD

**Issue by mxstbr** [styled-components/styled-components-website#82]
I know, I know, who needs SEO anyways? But if you google the site this is what you get:

![screen shot 2017-08-28 at 19 53 27](https://user-images.githubusercontent.com/7525670/29786214-99db384e-8c2a-11e7-97a5-bf0adbbafed3.png)

None of the content, and only the top-level pages are linked. (not even the sub-sections are there) Would much appreciate help so people can find the content on the website more easily!

**Comment by philpl** [comment]
> Diese Seite übersetzen

Subliminal message from Google to push #70 haha

This should be simple enough. Now that we have markdown, it should be possible to extract some page information automatically even? But since the main docs pages contain sub sections none of the content might be relevant.

Maybe the best thing to do is to just list the sub sections in the descriptions?

Both is not that nice, I'd love some input and ideas ❇️

**Comment by mxstbr** [comment]
I think we can probably somehow tell Google that the subsections are pages, linkable with the hashes, I'm just not 100% sure how to do that!

**Comment by harshmaur** [comment]
Guys, why arent we using next/head to define title and descriptions for each page? I know a bunch of other tags as well that are good for SEO purposes.

**Comment by mxstbr** [comment]
> Guys, why arent we using `next/head` to define title and descriptions for each page? I know a bunch of other tags as well that are good for SEO purposes.

PRs very _very_ welcome!!

**Comment by harshmaur** [comment]
@mxstbr Can you give me all the social media pages of styled-components? I am creating the schemas, breadcrumbs etc.

**Comment by mxstbr** [comment]
The only "social media" we have at the moment is Medium, that's all: https://medium.com/styled-components

**Comment by harshmaur** [comment]
Any plans to create other accounts? twitter atleast? or shall I use @mxstbr as the handle?

**Comment by philpl** [comment]
Fixed in #92

@mxstbr Should be sufficient, right?

**Comment by mxstbr** [comment]
Opening because I want to remember to add it to Google Webmaster Tools, let's see what that says we need to do!

**Comment by harshmaur** [comment]
Hey, lets do this. Its just a meta tag it asks you to add.
