### ISSUE TITLE
Figure out navigation

### ISSUE THREAD

**Issue by mxstbr** [styled-components/styled-components-website#83]
Right now, even on a large screen, large portions of the nav are cut off:

![screen shot 2017-08-28 at 19 56 14](https://user-images.githubusercontent.com/7525670/29786321-04ecc8e6-8c2b-11e7-9cc6-6e7f7bcb15fe.png)

That's not good, and it'll only get worse as we add more content to the site. We should figure out a better way of doing navigation.

We need a top nav for the "big pages" that should persist across all pages. (Homepage, Docs, Docs -> Basics, Docs -> Advanced, Docs -> FAQ, Docs -> Tooling, etc) We'll then likely still need some sort of side nav for the docs pages to navigate within them.

Any design/layout ideas and implementations welcome!

**Comment by morajabi** [comment]
Should we continue about nav and other stuff here or on the Spectrum?

**Comment by mxstbr** [comment]
Let's continue here so everybody can chime in, this is better suited for the design discussion!

**Comment by SaraVieira** [comment]
How about the inner pages being dropdown when you click the main page ?

**Comment by wking-io** [comment]
I really like the top nav with conditional side nav option! I think that could work really well making the top nav the gradient background and then the side nav being a lighter gray to differentiate it from the main content. 

I think the logo could then be broken into the icon on the left and styled components text beside it. Then on mobile the text can be removed and only the icon is there. 

I can make a mockup when I get back on my computer.

**Comment by mxstbr** [comment]
I quite like the two navigations! A couple of points:

- What about showing all sections in the sidebar but collapse them except for the one you're on. So in your case you're on Basics, so it'd show Basics + all the subpages, and then beneath that it'd show "Advanced", "API Reference" and "FAQ" but without their subpages listed?
- That frees us up on the top bar to do more things there. Since we're adding a bunch more broad sections like "Tooling" that'd get filled up pretty quick. We'll also add stuff like a search input (ref #85) etc. What do you think about just making it list "Home" and "Docs", and then having a search input?

**Comment by philpl** [comment]
I really like it as well :) two things however: I think the gradient is a bit off but don’t worry, since it’s already present in the code; second thing is the content container size. The one we have fits the content really well and the one in the design is too wide, so I’d probably preserve the current one.

Apart from that this looks really awesome! Maybe I should try to work on a first version? I actually do have time today. That is, if no one else is more stoked and motivated than i am ;)

**Comment by mxstbr** [comment]
Do it!

I'm not sure I like the gradient at the top (too much imo, the one on the homepage is enough; I'm not a fan of our current sidebar one either) and the android-like treatment if the selected states but I think this would be a great prototype to get out :blush:

**Comment by morajabi** [comment]
What about my design on nav? It seems you’re going with this one.

**Comment by philpl** [comment]
@mxstbr 

> I'm not sure I like the gradient at the top (too much imo, the one on the homepage is enough; I'm not a fan of our current sidebar one either)

Wut! 😆 That's A1 branding right here

**Comment by wking-io** [comment]
> second thing is the content container size. The one we have fits the content really well and the one in the design is too wide, so I’d probably preserve the current one.

I think I just have a larger screen! It was not my intention to redesign the content haha

I think the plan with the main nav being more universal links is better! Was not aware of the expansion of the site!

Also, I agree! part of the brand to me is the gradient now, but I think that it could just be the palevioletred as well and get the job done. 💯

**Comment by philpl** [comment]
@wking-io no worries! Just a note on my end regarding the sizing

The gradient is actually a big question on my end here. I wasn’t aware that you’re more in favour of a more simple design, @mxstbr. Maybe we need some more feedback on some variations? It’d be simple to tweet out a plain flat-colour navigation bar vs the gradient one. I’m definitely in favour of only having the gradient on the navbar and not the sidebar. It makes it less attention grabbing.

The gradient in general was an attempt to transition the branding from a brutalist approach to a minimalistic one. And overall people have reacted supportive of it, including @geelen. The navbar is certainly another question, but it does carry over some “fun” aspects and sets it apart from other sites.

Happy to hear everyone’s thoughts on this 😬

**Comment by philpl** [comment]
Oh, btw, regarding the navbar + sidebar. I’d really love to reconcile this effort with @morajabi’s work. We’ll also need to think of the collapsed sidebar for mobile devices / smaller screens. In those cases it’s probably impossible to get around scrolling, but we have to design and think about it beforehand. For instance, a DropDown is good on desktop but horrible on touch devices, and scrolling will be necessary still on smaller screens and phones

**Comment by morajabi** [comment]
I think putting documentation heading in the sidebar is the best to navigate them easily. You should let the nav bar handle other things like what Babel, Webpack, Jest, React and others did and use a sidebar for content navigation. Anyway, it's my opinion :)

I think what Redux did for navigation on mobile with a ||| (rotate 90deg) icon is great for mobile users. 

![screen shot 2017-08-29 at 7 57 30 pm](https://user-images.githubusercontent.com/12202757/29829310-53bd0b1a-8cf4-11e7-9949-1c2c3c1a8558.png)
![screen shot 2017-08-29 at 7 57 22 pm](https://user-images.githubusercontent.com/12202757/29829311-53c2f0ac-8cf4-11e7-8037-ef002de4b020.png)

**Comment by morajabi** [comment]
> For instance, a DropDown is good on desktop but horrible on touch devices, and scrolling will be necessary still on smaller screens and phones

What do you mean by scrolling? Where?

**Comment by morajabi** [comment]
> What about showing all sections in the sidebar but collapse them except for the one you're on. So in your case you're on Basics, so it'd show Basics + all the subpages, and then beneath that it'd show "Advanced", "API Reference" and "FAQ" but without their subpages listed?

@mxstbr I like this idea and it's more common in latest libs' docs.

**Comment by philpl** [comment]
@morajabi 

> What do you mean by scrolling? Where?

That navigation sidemenu might collapse on small screens. But since the screen is not only not wide enough, but also not long enough, you'll need to be able to scroll the content. So we might get rid of scrolling on desktop, but not on mobile. Which is ok! We just need to remember this.

Btw; Here's instead of the screenshots a gif. @morajabi feel free to remove the images; I think this illustrates what we'd like a bit better :)

![2017-08-29 16_39_06](https://user-images.githubusercontent.com/2041385/29830044-fb6662ce-8cd8-11e7-912a-0ba308e8d223.gif)

**Comment by morajabi** [comment]
Of course, GIF is better :) @philpl 

What's your opinion on having Basic, Advanced and FAQ parts in the sidebar? (Read my earlier messages)

**Comment by mxstbr** [comment]
> The gradient is actually a big question on my end here.

It's works super well on the homepage, but it feels forced and weird on the navbar to me. The navbar is a utility, it shouldn't be the first thing you look at when you look at the page?

I like where these designs are going, I can see the dropdowns in the nav working too!

**Comment by morajabi** [comment]
I think we should start to sum up what we expect from a nav, shouldn't we?

**Comment by wking-io** [comment]
> The navbar is a utility, it shouldn't be the first thing you look at when you look at the page

Agreed! When you put it like that I think that @morajabi is right and we should outline the priority/hierarchy of the pages so we know where the focus is. Because it the above is true then I think we can really reduce the design and make the content on the pages themselves the focus.

**Comment by mxstbr** [comment]
I think the content should be the focus.

People don't come to styled-components.com because they want eye candy, they come either because they want to try it (that's why the getting started is on the homepage) or because have an issue and are trying to fix it asap before their boss comes and screams in their faces. :wink:

**Comment by mxstbr** [comment]
That tells me that the top nav could be responsible to jump between the big sections ("Basics", "Advanced",...), but what I'm fearing is that we're going to run out of space as we add more and more content. (like just yesterday the new "Tooling" section, we might add "Guides", "Examples", "Integrations", etc. in the future)

So imo it makes more sense for the sidebar to be responsible for jumping within the documentation, while the top bar is responsible for search and navigating to the docs in the first place?

**Comment by morajabi** [comment]
@mxstbr As I said that before, I agree so much.

**Comment by philpl** [comment]
@mxstbr I agree with the navbar not containing pages of the docs. It can pretty much be the same across all pages, be it the docs or the homepage.

I also agree that the gradient feels attention-grabbing and forced right now. It’s force though in the sense of it being there for branding. And I think that’s alright. We should make it identifiable. That doesn’t hinder usability if we fix the attention grabbing part.

I’d say we should try out two designs: Navbar with the gradient and navbar with the pale violet red-like colour. Then we can see what both look like and let our users decide what they like the best

**Comment by morajabi** [comment]
@philpl If you can, I think it'd be great to write what you like about two design so I can make a new design. (Maybe edit your message above!)

**Comment by philpl** [comment]
@morajabi to combine all points (but ignoring the gradient for now):

- The navbar should be using our violetred colour (`rgb(219, 112, 147)`)
- It should use the compact version of our logo (the one that's already present today for mobile)
- It should not break up the text (This is up for debate, but I'd say we should keep it simple for now)
- It should avoid (i.e. not use) dropdowns (for the sake of mobile devices)
- It should incorporate the sidemenu, which has a light grey-ish colour, nicely
- The navbar should not contain links to the docs' pages but have the same links globally
- On mobile devices the navbar should contain a fold-button to open and close the sidemenu (See gif)
- The navbar needs to contain a search field (for future functionality) and maybe some links to Spectrum, Github, etc

Unanswered questions:

- Where do the navbar content go on mobile? Should the sidebar double for the docs links and the navbar links on mobile?

I think that covers it right now? cc @mxstbr

**Comment by morajabi** [comment]
@philpl  I will give it a hand if everyone is OK. Let me know.

**Comment by mxstbr** [comment]
Yes please!

**Comment by morajabi** [comment]
@philpl What do you mean by this?

> It should not break up the text

**Comment by morajabi** [comment]
@mxstbr @philpl I've redesigned the parts and added some artboards and notes for each state. I copied the nav and changed the colour to see if it's what we like.

I'd appreciate your comments on that. And we can edit the parts which are not your preference.
https://www.figma.com/file/ZZHoPeTYKNtNqcLYnRsQSVxR/Styled-Components

**Comment by philpl** [comment]
@morajabi sorry, that was a bit unclear:

> It should not break up the text

... of the "styled-components" wording on the left

**Comment by morajabi** [comment]
@philpl I'm glad you liked it!

> I'd like to see whether we can make due with the change above, even though it takes up more space. I don't necessarily want to perpetuate the "styled components" (no dash) name even more.

I see, What font & styling should I use for the **styled components**?

**Comment by philpl** [comment]
@morajabi So there's a couple of options here:

- Use the typography as is in the logo (with the line break which doesn't contain the dash, but seems to fit in the navbar nicely)
- Use the body font (that's probably not a good idea, since we can just export a png)
- Use the `styled-components` on a single line with the appropriate font

I actually realised that your design almost matches the logo but changed the `styled` part of it to appear in bold. That's what confused me initially, and we can't change details like these unfortunately. I think it'd be best just to export the typography with the logo to the right side.

You can find the resources here: https://github.com/styled-components/brand

In case you don't have Sketch, I can export it in the format you need later today

**Comment by morajabi** [comment]
@philpl That was just a quick placeholder! I have Sketch actually but I used Figma because it has better collaboration support.

**Comment by morajabi** [comment]
What do you think now? @philpl

**Comment by philpl** [comment]
@morajabi That looks perfect! Just have to make sure to export the wording of the logo as an image when we actually build this as we're not using Fira Sans anywhere else on the site :)

**Comment by morajabi** [comment]
That's OK but if we're going to import other fonts from Google, we can import just the letters s,t,y,l,e,d,c,o,m,p,n from Fira Sans like this:
https://fonts.googleapis.com/css?family=Fira+Sans:500&text=styledcompn
as discussed [here](https://stackoverflow.com/questions/18641479/use-a-google-font-and-include-only-a-z-and).

**Comment by mxstbr** [comment]
I love it, getting there for sure!

**Comment by morajabi** [comment]
Wow! I really appreciate that @mxstbr

**Comment by mxstbr** [comment]
Since nobody has commented in the negative yet, let's implement this? :blush:

**Comment by morajabi** [comment]
Great! Is it OK I start doing this tomorrow?

**Comment by mxstbr** [comment]
Sounds great to me!

**Comment by morajabi** [comment]
One question, should I implement it on a branch of the current website? Is home page going to be like this? I think it's not going to match the navbar.

**Comment by mxstbr** [comment]
Yeah, implement it on a branch and submit a PR!

> Is home page going to be like this?

I think we'll have to do some special treatment to the navbar on the homepage (no background?!) but let's figure that out once we have a first version (i.e. a WIP PR) and can quickly iterate?

**Comment by morajabi** [comment]
Should navbar be sticky?

**Comment by mxstbr** [comment]
I don't think so, just because it takes away a lot of screen estate on mobile and doesn't really improve the experience, right?

**Comment by morajabi** [comment]
I think it should be sticky on mobile because it's the only handler to unfold the side nav.

**Comment by mxstbr** [comment]
Ah yeah, that's true. Good point let's make it sticky!

**Comment by morajabi** [comment]
OK! What about the desktop? I don't think it's necessary there, what do you think?

**Comment by morajabi** [comment]
Progress Report: Going for the mobile menu view.

**Comment by morajabi** [comment]
Good news! It's finally done. I'm making the PR now so you can try it!

**Comment by morajabi** [comment]
@SaraVieira Can you take look? I'd be glad to know what you think, too!

**Comment by SaraVieira** [comment]
@morajabi I will do that tonight 🎉
