### ISSUE TITLE
Scroll bar in the x-axis

### ISSUE THREAD

**Issue by lostgirljourney** [styled-components/styled-components-website#837]
![image](https://user-images.githubusercontent.com/56036475/153351393-9dd389f2-5d6c-4873-ba33-42bc8129cad0.png)

There's a scroll bar at the x-axis when we scroll down to the last of the page, which kills the overall look of the page and can be rectified.

**Comment by brnt-toast** [comment]
this is related to #825 .. I see that the Brave browser is being used here.  Switching UAs doesn't reproduce issue. Can you share more details? What device are you using, adblockers, etc...
