### ISSUE TITLE
 Issues loading css first render with third party private package

### ISSUE THREAD

**Issue by guilhermeccrz** [styled-components/styled-components-website#876]
I have this private package with styled components, but when i deploy it to the serverless i cant get the styled components load at the first render, only if i move to another page. If i try to reload the browser, the issue appears again. Search and try everything, anyone can clarify me?

My head is going to explode :(

My Private Pack Config
babel.lrc
![image](https://user-images.githubusercontent.com/8568238/189793557-8e090b97-4f19-489a-84b2-49187a601faf.png)

rollup config
![image](https://user-images.githubusercontent.com/8568238/189793608-48ce6833-448f-4177-b193-6e2c8fe8d2d4.png)

My App using the Private pack
balel.lrc
![image](https://user-images.githubusercontent.com/8568238/189793699-2e00f38b-2f8a-4fd4-b6cc-130bc5ded7b4.png)
nextConfig
![image](https://user-images.githubusercontent.com/8568238/189793731-b48084fe-386c-4fea-9b26-bb834397f8ce.png)

**Comment by probablyup** [comment]
This isn't a support forum, it's bug reporting for the s-c website. Thanks.
