### ISSUE TITLE
Help wanted, conversion to TS

### ISSUE THREAD

**Issue by probablyup** [styled-components/styled-components-website#902]
Hi friends! As of this issue the repo is now ready and supporting migrating page and component files to use TypeScript. For the most part, this will involve:

1. Renaming a file to us a `ts` or `tsx` extension (depending on the presence of JSX)

2. Updating any imports if necessary

3. Removing use of prop types in favor of function component argument defaults

4. Adding a type signature to styled components that consume props, e.g.

  ```tsx
  styled.div<{ $color: string }>`
    color: ${p => p.$color || 'red'};
  `
  ```

If you'd like to claim a file or folder, please comment on this thread to let other people know and start a PR! Thank you very much for helping out 😄

**Comment by brnt-toast** [comment]
I'll take a look this weekend

**Comment by redaktorscha** [comment]
Hi, I'd love to help. I'm newbie but have got a little experience with the JS -> TS refactoring, done such task before. I'd love to try and start with something small if it's possible

**Comment by probablyup** [comment]
> Hi, I'd love to help. I'm newbie but have got a little experience with the JS -> TS refactoring, done such task before. I'd love to try and start with something small if it's possible

I'd say pick a file and follow the steps in the OP :)

**Comment by redaktorscha** [comment]
> > Hi, I'd love to help. I'm newbie but have got a little experience with the JS -> TS refactoring, done such task before. I'd love to try and start with something small if it's possible
> 
> I'd say pick a file and follow the steps in the OP :)

Hi, I've picked 'Layout.ts' component and also 'media' and 'rem' utils that are related to this component. It's almost ready, but I'm not sure how to define properly  `inner` parameter of the `mobile` func. Compiler shows no error for `inner: RuleSet<any>` but I'd love to get rid of `any` if possible. Could you give me a hint? ;-)

**Comment by probablyup** [comment]
> > > Hi, I'd love to help. I'm newbie but have got a little experience with the JS -> TS refactoring, done such task before. I'd love to try and start with something small if it's possible
> > 
> > 
> > I'd say pick a file and follow the steps in the OP :)
> 
> Hi, I've picked 'Layout.ts' component and also 'media' and 'rem' utils that are related to this component. It's almost ready, but I'm not sure how to define properly `inner` parameter of the `mobile` func. Compiler shows no error for `inner: RuleSet<any>` but I'd love to get rid of `any` if possible. Could you give me a hint? ;-)

Thanks for taking this on! :) I think `ReturnType<typeof css>` probably is good so it stays in sync with the API.
