### ISSUE TITLE
Add Analytics

### ISSUE THREAD

**Issue by mxstbr** [styled-components/styled-components-website#91]
`micro-analytics` is nice and all, but doesn't quite give us what we need and I don't have time to improve it further.

Let's switch to something else. I'd love for the stats to be public, if that's not possible because it doesn't exist let's just use Google Analytics because it's easy?

**Comment by philpl** [comment]
> micro-analytics is nice and all, but doesn't quite give us what we need and I don't have time to improve it further.

It also seems to be a bit brittle and crashed every now and then, I believe... Although it could also just be Zeit's infra not being well suited for it.

I'd be in favour of Google Analytics. It's the obvious choice

**Comment by harshmaur** [comment]
I have added GA in mine. Let me create a PR. :)

**Comment by harshmaur** [comment]
Can I get the Analytics UA Code please?

**Comment by harshmaur** [comment]
Also, I am pretty bad with jest, it is throwing up an error when I am trying to update the snapshot, it seems like it is coming from the library itself. Not sure how I can fix that. https://cl.ly/150H1C3T2v1N

**Comment by harshmaur** [comment]
I am actually done with the changes, Just need to solve the Jest issue.

**Comment by mxstbr** [comment]
It seems like `react-ga` can't be server-side rendered?

**Comment by harshmaur** [comment]
I am not sure. It works in my project. I don't use tests though. 

Secondly GA should be executed on frontend only right?

**Comment by mxstbr** [comment]
Yeah it should only happen on the frontend, otherwise it'll seem like we have 2x the pageviews! I created a property on Google Analytics, the tracking ID is `UA-105613776-1` :blush:

**Comment by mxstbr** [comment]
This thread has a long discussion about this exact feature:

**Comment by harshmaur** [comment]
I've used the same thing with modifications. How about I remove the test and make a PR then you can have the tests pass?

**Comment by mxstbr** [comment]
> How about I remove the test and make a PR then you can have the tests pass?

Just submit the PR with the failing tests so we can take a look at it. Thanks!!
