### ISSUE TITLE
Set up redirection for moved/renamed docs pages

### ISSUE THREAD

**Issue by kitten** [styled-components/styled-components-website#93]
We've now for the first time moved a section (babel plugin) to a different URL. But a slight rename can also change the URL dramatically, which leads to previous links being dead / unusable. Together with anchors this can become really annoying as it might not be immediately obvious that a section is missing.

We need to add some "stub" entries to the `docs.json` that set up some simple redirection to the new location. I think this is crucial not to frustrate readers over time :+1:

**Comment by harshmaur** [comment]
Can you give the old url and the new url? I will create a 301 redirect middleware.

**Comment by philpl** [comment]
I'd go for a 302 (hope that's the right code?) instead of a 301 to not have a permanent redirection in place.

The URL in question is: https://www.styled-components.com/docs/advanced#babel-plugin
It now lives at: https://www.styled-components.com/docs/tooling#babel-plugin

It'd be great to define these rules here: https://github.com/styled-components/styled-components-website/blob/master/pages/docs.json

Under a new key, like `movedPages`

**Comment by harshmaur** [comment]
Why do you want a 302? Is it a temporary change? The browser would work fine though, Google however would not record the change and will always follow the old url in this case.

**Comment by philpl** [comment]
@harshmaur 

> Google however would not record the change and will always follow the old url in this case.

Oh that's unfortunate

> Why do you want a 302? Is it a temporary change?

I think a simple 301 won't pick up on the hash/anchor part of the URL, right? I might be mistaken. Either way, I'd like to be careful about permanent, cached redirections that make it impossible to undo anything.

**Comment by harshmaur** [comment]
Hash/Anchor arent picked up by the server IMO, they are only browser based, I tried to get the hash, I could not get it in the request 

Check this https://stackoverflow.com/questions/9967681/nodejs-url-with-hash

So basically this has to be picked up on the frontend and redirection should happen which again is not a good way. Please suggest.

**Comment by philpl** [comment]
> So basically this has to be picked up on the frontend and redirection should happen which again is not a good way. Please suggest.

We can add a `componentDidMount` to our document and detect whether a redirect is necessary here: https://github.com/styled-components/styled-components-website/blob/master/pages/_document.js

**Comment by harshmaur** [comment]
Won't work. document.js only executes server side.

**Comment by philpl** [comment]
@harshmaur we can actually use the API to inject an HOC around the app and detect it there. It’s currently non-standard I.e. not released on next yet, but we’ve got it in our censored version to make styling ssr work

**Comment by harshmaur** [comment]
I am not aware, Could you explain more? I would then be able to do it. Also redirection on the frontend is not that pretty with nextjs. https://github.com/zeit/next.js/wiki/Redirecting-in-%60getInitialProps%60

**Comment by philpl** [comment]
@harshmaur here we’re wrapping the app in our StyleSheetManager. You can just create another Redirect component that wraps it as well and use and add the redirect logic to componentDidMount

https://github.com/styled-components/styled-components-website/blob/master/pages/_document.js#L150

**Comment by harshmaur** [comment]
I see!! Let me try to do it now.

**Comment by mckernanin** [comment]
@harshmaur need any help here?

**Comment by harshmaur** [comment]
@mckernanin Hey! You can take this up!
