### ISSUE TITLE
Upgrade next to version 3 as soon as 3.0.7 is released

### ISSUE THREAD

**Issue by kitten** [styled-components/styled-components-website#94]
Currently we have a vendored version of next: https://github.com/styled-components/styled-components-website/blob/master/vendor/next-v2.4.8.tgz

This is to work around our styling problem that prevented us from wrapping the entire app. A fix was proposed here but wasn't merged for a long time: https://github.com/zeit/next.js/pull/2010

Now that it was merged we can get rid of the vendored version and upgrade to v3, as soon as the fix lands in the next patch release

**Comment by mxstbr** [comment]
Except I couldn't get it to work: https://github.com/zeit/next.js/pull/2831

**Comment by philpl** [comment]
@mxstbr that explains why we end up with duplicated rules on the client... oops, I forgot about it running on the client as well. we can keep it as is, but update it once we find a workaround?

**Comment by mxstbr** [comment]
Let's just try and find a workaround? :laughing: We're going to need to put it in the Next docs anyway asap so not more people ship with an unnecessarily slow setup.

**Comment by arunoda** [comment]
Guys, `next@3.1.0` is with the change you guys are looking for.

**Comment by kachkaev** [comment]
@philpl what do you think of making this change? Next 3.2.2 is out :–)

**Comment by SaraVieira** [comment]
@kachkaev you can give it a shot! We would love that 🙌

**Comment by mckernanin** [comment]
Closing, as there's work in progress to get up to next 5: #232
