### ISSUE TITLE
Ecosystem page

### ISSUE THREAD

**Issue by mxstbr** [styled-components/styled-components-website#99]
Rather than having a huge list of related libraries in our README we should move that to the website! Could be structured into "one-off npm components you can use built with s-c", "component libraries" "grids" and "others" or something.

**Comment by morajabi** [comment]
"utilities" too.

**Comment by SaraVieira** [comment]
This will be closed by #123 right?

**Comment by mxstbr** [comment]
Oh, yeah, good call @SaraVieira!

**Comment by morajabi** [comment]
Except this:
> Rather than having a huge list of related libraries in our README.

**Comment by mxstbr** [comment]
It's no longer in our README, it's moved to https://github.com/styled-components/awesome-styled-components. That's fine with me since it's a "standard" and not everybody enjoys looking at our beautiful website :wink:

**Comment by morajabi** [comment]
> It's no longer in our README
Sorry! We solved this issue by two PRs.
